/**
 * Assembles the complete anatomy model (vessels, regions, perfusion beds) from the
 * hand-authored definitions and the data generated by tools/build_assets.py.
 */

import bedsJson from './generated/beds.json';
import vesselPaths from './generated/vesselPaths.json';
import { expandSupply, expandVessels, regionSides, vid } from './expand';
import { REGION_DEFS } from './regions';
import { bedSupply } from './territories';
import type { Bed, L, Lang, Region, RegionDef, SideOrMid, TerritoryCode, Vec3, Vessel } from './types';
import { VESSEL_DEFS } from './vessels';
import { indexById } from './indexById';

export * from './types';

interface RawBed {
  id: string;
  region: string;
  terr: string[];
  volume: number;
}

/**
 * The MNI152 template brain is larger than an average adult brain; bed volumes measured on
 * it are scaled so the whole brain totals ~1,250 mL (a typical adult value) — this matters
 * for volume-based thresholds such as "malignant MCA infarction > 145 mL".
 */
export const TARGET_BRAIN_VOLUME = 1250;

const paths = vesselPaths as unknown as Record<string, Vec3[]>;

export const VESSELS: Vessel[] = expandVessels(VESSEL_DEFS).map((v) => ({
  ...v,
  path: paths[v.id] && paths[v.id].length >= 2 ? paths[v.id] : v.path,
}));

export const VESSEL_BY_ID: Record<string, Vessel> = indexById(VESSELS, (v) => v.id);

const DEF_BY_BASE: Record<string, RegionDef> = indexById(REGION_DEFS, (d) => d.id);

const splitRegion = (rid: string): { base: string; side: SideOrMid } => {
  const m = /^(.*)_(r|l)$/.exec(rid);
  return m ? { base: m[1], side: m[2] as SideOrMid } : { base: rid, side: 'm' };
};

function buildBeds(): { beds: Bed[]; scale: number } {
  const raw = bedsJson as RawBed[];
  const rawTotal = raw.reduce((a, b) => a + b.volume, 0);
  const scale = TARGET_BRAIN_VOLUME / rawTotal;
  const beds: Bed[] = [];
  const seenRegions = new Set<string>();
  for (const b of raw) {
    const { base, side } = splitRegion(b.region);
    const def = DEF_BY_BASE[base];
    if (!def) throw new Error(`bed ${b.id} refers to unknown region ${base}`);
    seenRegions.add(b.region);
    const terr = b.terr as TerritoryCode[];
    const supply = terr.length ? bedSupply(base, terr) : def.supply ?? [];
    const volume = b.volume * scale;
    beds.push({
      id: b.id,
      region: b.region,
      terr,
      volume,
      supply: expandSupply(supply, side),
      baseFlow: (volume * def.cbf) / 100,
    });
  }
  // regions not measured by the pipeline (small tracts, non-brain beds)
  for (const def of REGION_DEFS) {
    for (const side of regionSides(def)) {
      const rid = vid(def.id, side);
      if (seenRegions.has(rid)) continue;
      const volume = def.fixedVolume ?? 0;
      beds.push({
        id: rid,
        region: rid,
        terr: [],
        volume,
        supply: expandSupply(def.supply ?? [], side),
        baseFlow: def.flow ?? (volume * def.cbf) / 100,
      });
    }
  }
  return { beds, scale };
}

const built = buildBeds();
export const BEDS: Bed[] = built.beds;
export const VOLUME_SCALE = built.scale;
export const BED_BY_ID: Record<string, Bed> = indexById(BEDS, (b) => b.id);

function buildRegions(): Region[] {
  const bedsByRegion = new Map<string, Bed[]>();
  for (const b of BEDS) {
    if (!bedsByRegion.has(b.region)) bedsByRegion.set(b.region, []);
    bedsByRegion.get(b.region)!.push(b);
  }
  const out: Region[] = [];
  for (const def of REGION_DEFS) {
    for (const side of regionSides(def)) {
      const id = vid(def.id, side);
      const beds = bedsByRegion.get(id) ?? [];
      const { bilateral: _b, supply: _s, nameBySide, fixedVolume: _f, id: baseId, ...rest } = def;
      void _b;
      void _s;
      void _f;
      out.push({
        ...rest,
        name: side !== 'm' && nameBySide?.[side] ? nameBySide[side]! : def.name,
        sideInName: side !== 'm' && !!nameBySide?.[side],
        id,
        baseId,
        side,
        volume: beds.reduce((a, b) => a + b.volume, 0),
        beds: beds.map((b) => b.id),
      });
    }
  }
  return out;
}

export const REGIONS: Region[] = buildRegions();
export const REGION_BY_ID: Record<string, Region> = indexById(REGIONS, (r) => r.id);

/** Localised text helper. */
export const tr = (l: L, lang: Lang): string => (lang === 'en' ? l.en : l.zh);

export const sideLabel = (side: SideOrMid, lang: Lang): string => {
  if (side === 'm') return '';
  if (lang === 'en') return side === 'r' ? 'Right' : 'Left';
  return side === 'r' ? '右側' : '左側';
};

/** "Middle cerebral artery" → "middle cerebral artery", but keep acronyms such as "ICA" or "MCA". */
const lowerFirst = (n: string) => (/^[A-Z][a-z]/.test(n) ? n.charAt(0).toLowerCase() + n.slice(1) : n);

/** Region display name including side. */
export function regionName(r: Region, lang: Lang): string {
  const n = tr(r.name, lang);
  if (r.side === 'm' || r.sideInName) return n;
  return lang === 'en' ? `${sideLabel(r.side, lang)} ${lowerFirst(n)}` : `${sideLabel(r.side, lang)}${n}`;
}

/** Vessel display name including side. */
export function vesselName(v: Vessel, lang: Lang): string {
  const n = tr(v.name, lang);
  if (v.side === 'm') return n;
  return lang === 'en' ? `${sideLabel(v.side, lang)} ${lowerFirst(n)}` : `${sideLabel(v.side, lang)}${n}`;
}

/** Sanity checks used by tests. */
export function validateAnatomy(): string[] {
  const errors: string[] = [];
  const nodes = new Set<string>();
  for (const v of VESSELS) {
    nodes.add(v.from);
    nodes.add(v.to);
    if (v.parent && !VESSEL_BY_ID[v.parent]) errors.push(`${v.id}: unknown parent ${v.parent}`);
    for (const end of [v.from, v.to]) {
      if (end.endsWith('@mid') && !VESSEL_BY_ID[end.slice(0, -4)]) errors.push(`${v.id}: bad mid ref ${end}`);
    }
    if (v.path.length < 2) errors.push(`${v.id}: path too short`);
  }
  for (const b of BEDS) {
    if (!REGION_BY_ID[b.region]) errors.push(`bed ${b.id}: unknown region`);
    if (b.supply.length === 0) errors.push(`bed ${b.id}: no supply`);
    for (const s of b.supply) if (!VESSEL_BY_ID[s.v]) errors.push(`bed ${b.id}: unknown vessel ${s.v}`);
  }
  return errors;
}
