/**
 * Third-party data and scientific sources used by the app. Rendered in the in-app
 * "Sources & licences" dialog and mirrored in THIRD_PARTY_NOTICES.md.
 */

import type { L } from './types';

export interface DataSource {
  id: string;
  name: string;
  use: L;
  licence: string;
  licenceUrl?: string;
  attribution: string;
  url: string;
  modified: boolean;
  /** licence text that must accompany copies */
  notice?: string;
}

/** Verbatim from the template's LICENSE file; required in all copies. */
export const MNI_NOTICE =
  'Copyright (C) 1993–2004 Louis Collins, McConnell Brain Imaging Centre, Montreal Neurological Institute, McGill University. Permission to use, copy, modify, and distribute this software and its documentation for any purpose and without fee is hereby granted, provided that the above copyright notice appear in all copies. The authors and McGill University make no representations about the suitability of this software for any purpose. It is provided “as is” without express or implied warranty. The authors are not responsible for any data loss, equipment damage, property loss, or injury to subjects or patients resulting from the use or misuse of this software package.';

export const DATA_SOURCES: DataSource[] = [
  {
    id: 'icbm152',
    name: 'MNI ICBM 152 Nonlinear Asymmetric 2009c template (via TemplateFlow)',
    use: {
      zh: '大腦、小腦、腦幹與深部核團的 3D 表面（由機率圖與分割結果以 marching cubes 產生、簡化）。',
      en: 'Surfaces of the cerebrum, cerebellum, brainstem and deep nuclei (marching-cubes meshes, decimated).',
    },
    licence: 'McGill/MNI permissive licence (copyright notice required)',
    attribution:
      'Copyright (C) 1993–2004 Louis Collins, McConnell Brain Imaging Centre, Montreal Neurological Institute, McGill University. Fonov V et al., NeuroImage 2011;54:313–327; Fonov V et al., NeuroImage 2009;47:S102. Distributed through TemplateFlow (Ciric R et al., Nat Methods 2022).',
    url: 'https://www.templateflow.org/ · http://nist.mni.mcgill.ca/icbm-152-nonlinear-atlases-2009/',
    modified: true,
    notice: MNI_NOTICE,
  },
  {
    id: 'dkt',
    name: 'DKT31 cortical labels in MNI152NLin2009cAsym (Mindboggle OASIS-TRT-20 joint fusion)',
    use: {
      zh: '皮質腦迴分區（決定每個表面點屬於哪個功能腦區）。',
      en: 'Cortical gyral parcellation (assigns each surface point to a functional region).',
    },
    licence: 'CC BY 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/4.0/',
    attribution: 'Klein A, Tourville J. 101 labeled brain images and a consistent human cortical labeling protocol. Front Neurosci 2012;6:171. Mindboggle-101 (Zenodo).',
    url: 'https://mindboggle.info/data',
    modified: true,
  },
  {
    id: 'aseg',
    name: 'FreeSurfer aseg segmentation of MNI152NLin2009cAsym (TemplateFlow)',
    use: {
      zh: '深部構造（視丘、尾狀核、殼核、蒼白球、海馬迴、杏仁核）與腦幹、小腦的分割。',
      en: 'Segmentation of deep nuclei, brainstem and cerebellum.',
    },
    licence: 'Template licence (McGill/MNI notice)',
    attribution: 'Fischl B et al. Neuron 2002;33:341–355 (FreeSurfer). Provided by TemplateFlow.',
    url: 'https://www.templateflow.org/',
    modified: true,
  },
  {
    id: 'mial',
    name: 'MIAL67 probabilistic atlas of thalamic nuclei',
    use: {
      zh: '把視丘分成前部、旁正中、腹外側、後部等血管供應區。',
      en: 'Splits the thalamus into anterior, paramedian, ventrolateral and posterior vascular territories.',
    },
    licence: 'CC BY 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by/4.0/',
    attribution: 'Najdenovska E et al. In-vivo probabilistic atlas of human thalamic nuclei based on diffusion-weighted MRI. Sci Data 2018;5:180270.',
    url: 'https://doi.org/10.5281/zenodo.1241074',
    modified: true,
  },
  {
    id: 'liu',
    name: 'Digital 3D Brain MRI Arterial Territories Atlas',
    use: {
      zh: '每個腦組織體素的動脈供應區（前、中、後大腦動脈各分部、豆紋、脈絡叢、小腦動脈），並據此找出分水嶺區。',
      en: 'Arterial territory of every tissue voxel (ACA, MCA and PCA subdivisions, lenticulostriate, choroidal, cerebellar), and the border zones between them.',
    },
    licence: 'CC BY-SA 4.0',
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0/',
    attribution:
      'Digital 3D Brain MRI Arterial Territories Atlas © 2021 The Johns Hopkins University. Liu CF, Hsu J, Xu X, et al. Sci Data 2023;10:74.',
    url: 'https://github.com/Chin-Fu-Liu/Arterial_Atlas',
    modified: true,
  },
  {
    id: 'mouches',
    name: 'Statistical atlas of cerebral arteries (multi-centre MRA)',
    use: {
      zh: '把手繪的血管中心線校正到統計上真實的血管位置（Willis 環、基底動脈、椎動脈、M1、A1/A2、P1/P2 等）。',
      en: 'Snaps hand-authored centrelines onto statistically real artery positions (circle of Willis, basilar, vertebral, M1, A1/A2, P1/P2 …).',
    },
    licence: 'CC0 1.0',
    licenceUrl: 'https://creativecommons.org/publicdomain/zero/1.0/',
    attribution: 'Mouches P, Forkert ND. A statistical atlas of cerebral arteries generated using multi-center MRA datasets from healthy subjects. Sci Data 2019;6:29.',
    url: 'https://doi.org/10.6084/m9.figshare.c.4215089',
    modified: true,
  },
];

export const SCIENTIFIC_REFERENCES: string[] = [
  // ── localised non-motor symptoms (sleep, emotional expression, temperature regulation, taste, bladder) ──
  'Bassetti C, Mathis J, Gugger M, Lovblad KO, Hess CW. Hypersomnia following paramedian thalamic stroke: a report of 12 patients. Ann Neurol 1996;39:471–480. (Persistent hypersomnia.)',
  'Bassetti CL. Sleep and stroke. Semin Neurol 2005;25:19–32. (Lasting sleep–wake disorders from thalamic or brainstem damage.)',
  'Bogousslavsky J, Khurana R, Deruaz JP, Hornung JP, Regli F, Janzer R, Perret C. Respiratory failure and unilateral caudal brainstem infarction. Ann Neurol 1990;28:668–673. (Loss of automatic breathing — 2 cases.)',
  'Grau AJ, Buggle F, Schnitzler P, Spiel M, Lichy C, Hacke W. Fever and infection early after ischemic stroke. J Neurol Sci 1999;171:115–120. (Why central fever is not modelled.)',
  'Heckmann JG, Stössel C, Lang CJ, Neundörfer B, Tomandl B, Hummel T. Taste disorders in acute stroke: a prospective observational study on taste disorders in 102 stroke patients. Stroke 2005;36:1690–1694.',
  'Hermann DM, Siccoli M, Brugger P, Wachter K, Mathis J, Achermann P, Bassetti CL. Evolution of neurological, neuropsychological and sleep-wake disturbances after paramedian thalamic stroke. Stroke 2008;39:62–68. (Course of hypersomnia, one- vs two-sided.)',
  'House A, Dennis M, Molyneux A, Warlow C, Hawton K. Emotionalism after stroke. BMJ 1989;298:991–994.',
  'Kim BS, Kim YI, Lee KS. Contralateral hyperhidrosis after cerebral infarction. Clinicoanatomic correlations in five cases. Stroke 1995;26:896–899.',
  'Kim JS. Post-stroke emotional incontinence after small lenticulocapsular stroke: correlation with lesion location. J Neurol 2002;249:805–810.',
  'Kim JS, Choi-Kwon S. Poststroke depression and emotional incontinence: correlation with lesion location. Neurology 2000;54:1805–1810. (Sites of pathological crying.)',
  'Kimura K, Tachibana N, Kohyama J, Otsuka Y, Fukazawa S, Waki R. A discrete pontine ischemic lesion could cause REM sleep behavior disorder. Neurology 2000;55:894–895. (Case report.)',
  'Korpelainen JT, Sotaniemi KA, Myllylä VV. Hyperhidrosis as a reflection of autonomic failure in patients with acute hemispheral brain infarction. An evaporimetric study. Stroke 1992;23:1271–1275.',
  'Korpelainen JT, Sotaniemi KA, Myllylä VV. Ipsilateral hypohidrosis in brain stem infarction. Stroke 1993;24:100–104.',
  'Korpelainen JT, Sotaniemi KA, Myllylä VV. Asymmetric sweating in stroke: a prospective quantitative study of patients with hemispheral brain infarction. Neurology 1993;43:1211–1214.',
  'Korpelainen JT, Sotaniemi KA, Myllylä VV. Asymmetrical skin temperature in ischemic stroke. Stroke 1995;26:1543–1547. (Cooler limbs opposite the infarct.)',
  'Labar DR, Mohr JP, Nichols FT 3rd, Tatemichi TK. Unilateral hyperhidrosis after cerebral infarction. Neurology 1988;38:1679–1682.',
  'Landis BN, Leuchter I, San Millán Ruíz D, Lacroix JS, Landis T. Transient hemiageusia in cerebrovascular lateral pontine lesions. J Neurol Neurosurg Psychiatry 2006;77:680–683. (Case report.)',
  'Mendoza M, Latorre JG. Pearls and oy-sters: reversible Ondine\'s curse in a case of lateral medullary infarction. Neurology 2013;80:e13–e16. (Case report.)',
  'Odd H, Dore C, Eriksson SH, Heydrich L, Bargiotas P, Ashburner J, Lambert C. Lesion network mapping of REM sleep behaviour disorder. Neuroimage Clin 2025;45:103751.',
  'Onoda K, Ikeda M, Sekine H, Ogawa H. Clinical study of central taste disorders and discussion of the central gustatory pathway. J Neurol 2012;259:261–266. (Side of taste loss by lesion level.)',
  'Pavšič K, Pretnar-Oblak J, Bajrović FF, Dolenc-Grošelj L. Prospective study of sleep-disordered breathing in 28 patients with acute unilateral lateral medullary infarction. Sleep Breath 2020;24:1557–1563.',
  'Rousseaux M, Hurtevent JF, Benaim C, Cassim F. Late contralateral hyperhidrosis in lateral medullary infarcts. Stroke 1996;27:991–995. (Not modelled.)',
  'Sacco S, Sarà M, Pistoia F, Conson M, Albertini G, Carolei A. Management of pathologic laughter and crying in patients with locked-in syndrome: a report of 4 cases. Arch Phys Med Rehabil 2008;89:775–778.',
  'Sakakibara R, Hattori T, Yasuda K, Yamanishi T. Micturitional disturbance and the pontine tegmental lesion: urodynamic and MRI analyses of vascular cases. J Neurol Sci 1996;141:105–110.',
  'Sung CY, Lee TH, Chu NS. Central hyperthermia in acute stroke. Eur Neurol 2009;62:86–92. (Why central fever is not modelled.)',
  'Tang WK, Hermann DM, Chen YK, Liang HJ, Liu XX, Chu WC, Ahuja AT, Abrigo J, Mok V, Ungvari GS, Wong KS. Brainstem infarcts predict REM sleep behavior disorder in acute ischemic stroke. BMC Neurol 2014;14:88.',
  'Tellenbach N, Schmidt MH, Alexiev F, Blondiaux E, Cavalloni F, Bassetti CL, Heydrich L, Bargiotas P. REM sleep and muscle atonia in brainstem stroke: a quantitative polysomnographic and lesion analysis study. J Sleep Res 2023;32:e13640. (Evidence against: no excess REM muscle activity.)',
  'Wanklyn P, Ilsley DW, Greenstein D, Hampton IF, Roper TA, Kester RC, Mulley GP. The cold hemiplegic arm. Stroke 1994;25:1765–1770.',
  'Wanklyn P, Forster A, Young J, Mulley G. Prevalence and associated features of the cold hemiplegic arm. Stroke 1995;26:1867–1870.',
  'Xi Z, Luning W. REM sleep behavior disorder in a patient with pontine stroke. Sleep Med 2009;10:143–146. (Case report.)',
  // ── audit (chain A: cortex, deep structures, medulla and cerebellum, late and non-motor, NIHSS rules) ──
  // ── flow, tissue and clinical model ──
  'Alastruey J, Parker KH, Peiró J, Byrd SM, Sherwin SJ. Modelling the circle of Willis to assess the effects of anatomical variations and occlusions on cerebral flows. J Biomech 2007;40:1794–1805. (Vessel dimensions; also the openBF implementation, Apache-2.0.)',
  'Astrup J, Siesjö BK, Symon L. Thresholds in cerebral ischemia – the ischemic penumbra. Stroke 1981;12:723–725. (The penumbra concept.)',
  'Campbell BCV et al. Cerebral blood flow is the optimal CT perfusion parameter for assessing infarct core. Stroke 2011;42:3435–3440.',
  'Saver JL. Time is brain—quantified. Stroke 2006;37:263–266.',
  'Albers GW et al. Magnetic resonance imaging profiles predict clinical response to early reperfusion: the DEFUSE study. Ann Neurol 2006;60:508–517.',
  'Davis SM et al. Effects of alteplase beyond 3 h after stroke in the Echoplanar Imaging Thrombolytic Evaluation Trial (EPITHET). Lancet Neurol 2008;7:299–309.',
  'Oppenheim C et al. Prediction of malignant middle cerebral artery infarction by diffusion-weighted imaging. Stroke 2000;31:2175–2181.',
  'Vahedi K et al. Early decompressive surgery in malignant infarction of the middle cerebral artery: a pooled analysis of three randomised controlled trials. Lancet Neurol 2007;6:215–222.',
  'Wijdicks EFM et al. Recommendations for the management of cerebral and cerebellar infarction with swelling. Stroke 2014;45:1222–1238.',
  'Schlaug G et al. Time course of the apparent diffusion coefficient (ADC) abnormality in human stroke. Neurology 1997;49:113–119.',
  'Lansberg MG et al. Evolution of apparent diffusion coefficient, diffusion-weighted, and T2-weighted signal intensity of acute stroke. AJNR Am J Neuroradiol 2001;22:637–644.',
  'Simard JM, Kent TA, Chen M, Tarasov KV, Gerzanich V. Brain oedema in focal ischaemia: molecular pathophysiology and theoretical implications. Lancet Neurol 2007;6:258–268.',
  'Minnerup J et al. Computed tomography-based quantification of lesion water uptake identifies patients within 4.5 hours of stroke onset. Ann Neurol 2016;80:924–934.',
  'Klatzo I. Neuropathological aspects of brain edema. J Neuropathol Exp Neurol 1967;26:1–14.',
  'Ayata C, Ropper AH. Ischaemic brain oedema. J Clin Neurosci 2002;9:113–124.',
  'Hacke W et al. \'Malignant\' middle cerebral artery territory infarction: clinical course and prognostic signs. Arch Neurol 1996;53:309–315.',
  'Ropper AH. Lateral displacement of the brain and level of consciousness in patients with an acute hemispheral mass. N Engl J Med 1986;314:953–958.',
  'Krabbe-Hartkamp MJ et al. Circle of Willis: morphologic variation on three-dimensional time-of-flight MR angiograms. Radiology 1998;207:103–111.',
  'Hindenes LB et al. Variations in the circle of Willis in a large population sample using 3D TOF angiography: the Tromsø Study. PLoS One 2020;15:e0241373.',
  'Dirnagl U, Iadecola C, Moskowitz MA. Pathobiology of ischaemic stroke: an integrated view. Trends Neurosci 1999;22:391–397.',
  'Pantano P, Baron JC, Samson Y, Bousser MG, Derouesne C, Comar D. Crossed cerebellar diaschisis. Further studies. Brain 1986;109(Pt 4):677–694.',
  'Kuhn MJ et al. Wallerian degeneration after cerebral infarction: evaluation with sequential MR imaging. Radiology 1989;172:179–182.',
  'Thomalla G et al. DTI detects early Wallerian degeneration of the pyramidal tract after ischemic stroke. NeuroImage 2004;22:1767–1774.',
  'Goto N, Kaneko M. Olivary enlargement: chronological and morphometric analyses. Acta Neuropathol 1981;54:275–282.',
  'Kitajima M et al. Hypertrophic olivary degeneration: MR imaging and pathologic findings. Radiology 1994;192:539–543.',
  'Tatu L, Moulin T, Bogousslavsky J, Duvernoy H. Arterial territories of the human brain: cerebral hemispheres. Neurology 1998;50:1699–1708.',
  'Tatu L, Moulin T, Bogousslavsky J, Duvernoy H. Arterial territories of human brain: brainstem and cerebellum. Neurology 1996;47:1125–1135.',
  'Schmahmann JD. Vascular syndromes of the thalamus. Stroke 2003;34:2264–2278.',
  'Brott T et al. Measurements of acute cerebral infarction: a clinical examination scale. Stroke 1989;20:864–870. (The original 15-item scale.)',
  'Donnan GA, Bladin PF, Berkovic SF, Longley WA, Saling MM. The stroke syndrome of striatocapsular infarction. Brain 1991;114(Pt 1A):51–70.',
  'Fisher CM. Lacunar strokes and infarcts: a review. Neurology 1982;32:871–876.',
  'Bamford J et al. Classification and natural history of clinically identifiable subtypes of cerebral infarction. Lancet 1991;337:1521–1526.',
  'Parvizi J, Damasio AR. Neuroanatomical correlates of brainstem coma. Brain 2003;126:1524–1536.',
  'Goyal M et al. Endovascular treatment of stroke due to medium-vessel occlusion (ESCAPE-MeVO). N Engl J Med 2025;392:1385–1395.',
  'Psychogios M et al. Endovascular treatment for stroke due to occlusion of medium or distal vessels (DISTAL). N Engl J Med 2025;392:1374–1384.',
  'Tao C et al. Trial of endovascular treatment of acute basilar-artery occlusion (ATTENTION). N Engl J Med 2022;387:1361–1372.',
  'Jovin TG et al. Trial of thrombectomy 6 to 24 hours after stroke due to basilar-artery occlusion (BAOCHE). N Engl J Med 2022;387:1373–1384.',
  'Lindsberg PJ et al. Time window for recanalization in basilar artery occlusion: speculative synthesis. Neurology 2015;85:1806–1815.',
  'Lindsberg PJ, Mattle HP. Therapy of basilar artery occlusion: a systematic analysis comparing intra-arterial and intravenous thrombolysis. Stroke 2006;37:922–928.',
  'van der Hoeven EJRJ et al. Collateral flow predicts outcome after basilar artery occlusion: the posterior circulation collateral score. Int J Stroke 2016;11:768–775.',
  'Alemseged F et al. The basilar artery on computed tomography angiography prognostic score (BATMAN). Stroke 2017;48:631–637.',
  'Ferbert A, Brückmann H, Drummen R. Clinical features of proven basilar artery occlusion. Stroke 1990;21:1135–1142.',
  'von Campe G, Regli F, Bogousslavsky J. Heralding manifestations of basilar artery occlusion with lethal or severe stroke. J Neurol Neurosurg Psychiatry 2003;74:1621–1626.',
  'Bauer G, Gerstenbrand F, Rumpl E. Varieties of the locked-in syndrome. J Neurol 1979;221:77–91.',
  'Patterson JR, Grabois M. Locked-in syndrome: a review of 139 cases. Stroke 1986;17:758–764.',
  'Casanova E et al. Locked-in syndrome: improvement in the prognosis after an early intensive multidisciplinary rehabilitation. Arch Phys Med Rehabil 2003;84:862–867.',
  'Plum F, Posner JB. The Diagnosis of Stupor and Coma (breathing patterns in brainstem lesions).',
  'Easton JD et al. Definition and evaluation of transient ischemic attack. Stroke 2009;40:2276–2293.',
  'Jones TH et al. Thresholds of focal cerebral ischemia in awake monkeys. J Neurosurg 1981;54:773–782.',
  'Wang Y et al. Clopidogrel with aspirin in acute minor stroke or transient ischemic attack (CHANCE). N Engl J Med 2013;369:11–19.',
  'Johnston SC et al. Clopidogrel and aspirin in acute ischemic stroke and high-risk TIA (POINT). N Engl J Med 2018;379:215–225.',
  'Hayreh SS et al. Central retinal artery occlusion: retinal survival time. Exp Eye Res 2004;78:723–736.',
  'Mac Grory B et al. Management of central retinal artery occlusion: a scientific statement from the American Heart Association. Stroke 2021;52:e282–e294.',
  'Lawrence DG, Kuypers HGJM. The functional organization of the motor system in the monkey: the effects of bilateral pyramidal lesions. Brain 1968;91:1–14.',
  'Baker SN. The primate reticulospinal tract, hand function and functional recovery. J Physiol 2011;589:5603–5612.',
  'Feeney DM, Baron JC. Diaschisis. Stroke 1986;17:817–830.',
  'Kwakkel G, Kollen B, Twisk J. Impact of time on improvement of outcome after stroke. Stroke 2006;37:2348–2353.',
  'Langhorne P, Bernhardt J, Kwakkel G. Stroke rehabilitation. Lancet 2011;377:1693–1702.',
  'Goyal M et al. Endovascular thrombectomy after large-vessel ischaemic stroke: a meta-analysis of individual patient data from five randomised trials (HERMES). Lancet 2016;387:1723–1731.',
  'Menon BK et al. J Neurointerv Surg 2019;11:1065–1069 (thrombectomy for M2 occlusions, HERMES).',
  'Nogueira RG et al. Thrombectomy 6 to 24 hours after stroke with a mismatch between deficit and infarct (DAWN). N Engl J Med 2018;378:11–21.',
  'Yang P et al. Endovascular thrombectomy with or without intravenous alteplase in acute stroke (DIRECT-MT). N Engl J Med 2020;382:1981–1993.',
  'Fischer U et al. Lancet 2022;400:104–115 (SWIFT DIRECT: thrombectomy alone vs. with intravenous alteplase).',
  'LeCouffe NE et al. A randomized trial of intravenous alteplase before endovascular treatment for stroke (MR CLEAN-NO IV). N Engl J Med 2021;385:1833–1844.',
  'Knapen RRMM et al. Cardiovasc Intervent Radiol 2025;48:1869–1877 (VERITAS pooled analysis of basilar artery occlusion trials).',
  'Strbian D et al. Eur Stroke J 2024;9:835–884 (ESO/ESMINT guideline on basilar artery occlusion).',
  'Yi T et al. Predictors of futile recanalization in basilar artery occlusion patients undergoing endovascular treatment: a post hoc analysis of the ATTENTION trial. Front Neurol 2023;14:1308036.',
  'Bhatia R et al. Low rates of acute recanalization with intravenous recombinant tissue plasminogen activator in ischemic stroke: real-world experience and a call for action. Stroke 2010;41:2254–2258.',
  'Menon BK et al. JAMA 2018;320:1017–1026 (INTERRSeCT: recanalisation after intravenous thrombolysis by occlusion site).',
  'Seners P et al. Stroke 2016;47:2409–2412 (early recanalisation after intravenous thrombolysis by occlusion site).',
  'Riedel CH et al. The importance of size: successful recanalization by intravenous thrombolysis in acute anterior stroke depends on thrombus length. Stroke 2011;42:1775–1777.',
  'The NINDS rt-PA Stroke Study Group. Tissue plasminogen activator for acute ischemic stroke. N Engl J Med 1995;333:1581–1587.',
  'Hacke W et al. Thrombolysis with alteplase 3 to 4.5 hours after acute ischemic stroke (ECASS III). N Engl J Med 2008;359:1317–1329.',
  'Wahlgren N et al. Thrombolysis with alteplase for acute ischaemic stroke in the Safe Implementation of Thrombolysis in Stroke-Monitoring Study (SITS-MOST). Lancet 2007;369:275–282.',
  'Alexandrov AV, Grotta JC. Arterial reocclusion in stroke patients treated with intravenous tissue plasminogen activator. Neurology 2002;59:862–867.',
  'Mosimann PJ et al. Stroke 2018;49:2643–2651 (reocclusion after thrombectomy).',
  'Marto JP et al. Stroke 2019;50:2960–2963 (early reocclusion after thrombectomy).',
  'Beyeler M et al. J Neurointerv Surg 2022;14:326–332 (emboli to new territories during thrombectomy).',
  'Singh N et al. Stroke 2023;54:1477–1483 (new-territory infarcts after thrombectomy, ESCAPE-NA1).',
  'Wong GJ et al. Stroke 2021;52:2241–2249 (embolic evidence on MRI before and after thrombectomy).',
  'Ng FC et al. Neurology 2022;98:e790–e801 (no-reflow after successful reperfusion).',
  'ter Schiphorst A et al. J Cereb Blood Flow Metab 2021;41:253–266 (tissue no-reflow after recanalisation).',
  'Hackett ML, Pickles K. Part I: frequency of depression after stroke: an updated systematic review and meta-analysis of observational studies. Int J Stroke 2014;9:1017–1025.',
  'Ayerbe L et al. Natural history, predictors and outcomes of depression after stroke: systematic review and meta-analysis. Br J Psychiatry 2013;202:14–21.',
  'Carson AJ et al. Depression after stroke and lesion location: a systematic review. Lancet 2000;356:122–126.',
  'Knapp P et al. Frequency of anxiety after stroke: an updated systematic review and meta-analysis of observational studies. Int J Stroke 2020;15:244–255.',
  'Wright F et al. Factors associated with poststroke anxiety: a systematic review and meta-analysis. Stroke Res Treat 2017;2017:2124743.',
  'Caeiro L, Ferro JM, Costa J. Apathy secondary to stroke: a systematic review and meta-analysis. Cerebrovasc Dis 2013;35:23–39.',
  'Gillespie DC et al. Prevalence of pseudobulbar affect following stroke: a systematic review and meta-analysis. J Stroke Cerebrovasc Dis 2016;25:688–694.',
  'Broomfield NM et al. Post-stroke emotionalism: diagnosis, pathophysiology, and treatment. Int J Stroke 2024;19:857–866.',
  'Cumming TB et al. The prevalence of fatigue after stroke: a systematic review and meta-analysis. Int J Stroke 2016;11:968–977.',
  'Kutlubaev MA, Duncan FH, Mead GE. Biological correlates of post-stroke fatigue: a systematic review. Acta Neurol Scand 2012;125:219–227.',
  'Baylan S et al. Incidence and prevalence of post-stroke insomnia: a systematic review and meta-analysis. Sleep Med Rev 2020;49:101222.',
  'Seiler A et al. Prevalence of sleep-disordered breathing after stroke and TIA: a meta-analysis. Neurology 2019;92:e648–e654.',
  'Johnson KG, Johnson DC. Frequency of sleep apnea in stroke and TIA patients: a meta-analysis. J Clin Sleep Med 2010;6:131–137.',
  'Yaggi HK et al. Obstructive sleep apnea as a risk factor for stroke and death. N Engl J Med 2005;353:2034–2041.',
  'Pendlebury ST, Rothwell PM. Prevalence, incidence, and factors associated with pre-stroke and post-stroke dementia: a systematic review and meta-analysis. Lancet Neurol 2009;8:1006–1018.',
  // ── audit (chain B: citations, treatment, haemodynamics, brainstem and thalamus, acute course) ──
  'Alamowitch S, Turc G, Palaiodimou L, et al. European Stroke Organisation (ESO) expedited recommendation on tenecteplase for acute ischaemic stroke. Eur Stroke J 2023;8:8–54. (Tenecteplase 0.25 mg/kg as an alternative to alteplase, preferred for large-vessel occlusion; not for stroke on waking selected with non-contrast CT alone.)',
  'Barow E, Boutitie F, Cheng B, et al. Functional outcome of intravenous thrombolysis in patients with lacunar infarcts in the WAKE-UP trial. JAMA Neurol 2019;76:641–649. (Lacunar strokes: alteplase effect not different from other strokes.)',
  'Bendszus M, Fiehler J, Subtil F, et al. Endovascular thrombectomy for acute ischaemic stroke with established large infarct: multicentre, open-label, randomised trial (TENSION). Lancet 2023;402:1753–1763.',
  'Campbell BCV, Mitchell PJ, Churilov L, et al. Tenecteplase versus alteplase before thrombectomy for ischemic stroke (EXTEND-IA TNK). N Engl J Med 2018;378:1573–1582.',
  'Costalat V, Jovin TG, Albucher JF, et al. Trial of thrombectomy for stroke with a large infarct of unrestricted size (LASTE). N Engl J Med 2024;390:1677–1689.',
  'de Bastos Maximiano ML, Gonçalves OR, Falcão L, et al. Endovascular treatment in patients with cervical or intracranial isolated internal carotid artery occlusion: a systematic review and meta-analysis. Neuroradiol J 2026;39:557–566.',
  'Fiorelli M, Bastianello S, von Kummer R, et al. Hemorrhagic transformation within 36 hours of a cerebral infarct: relationships with early clinical deterioration and 3-month outcome in the European Cooperative Acute Stroke Study I (ECASS I) cohort. Stroke 1999;30:2280–2284.',
  'Huo X, Ma G, Tong X, et al. Trial of endovascular therapy for acute ischemic stroke with large infarct (ANGEL-ASPECT). N Engl J Med 2023;388:1272–1283.',
  'Kargiotis O, Psychogios K, Safouris A, et al. Diagnosis and treatment of acute isolated proximal internal carotid artery occlusions: a narrative review. Ther Adv Neurol Disord 2022;15:17562864221136335.',
  'Lyden P, Brott T, Tilley B, Welch KM, Mascha EJ, Levine S, Haley EC, Grotta J, Marler J. Improved reliability of the NIH Stroke Scale using video training. NINDS TPA Stroke Study Group. Stroke 1994;25:2220–2226. (The NIHSS as used in the NINDS t-PA trial, with video certification.)',
  'Ma H, Campbell BCV, Parsons MW, et al. Thrombolysis guided by perfusion imaging up to 9 hours after onset of stroke (EXTEND). N Engl J Med 2019;380:1795–1803.',
  'Menon BK, Buck BH, Singh N, et al. Intravenous tenecteplase compared with alteplase for acute ischaemic stroke in Canada (AcT): a pragmatic, multicentre, open-label, registry-linked, randomised, controlled, non-inferiority trial. Lancet 2022;400:161–169.',
  'Prabhakaran S, Gonzalez NR, Zachrison KS, et al. 2026 Guideline for the early management of patients with acute ischemic stroke: a guideline from the American Heart Association/American Stroke Association. Stroke 2026;57:e316–e436. (Key updates include thrombolytic choice and eligibility; cited at abstract level only.)',
  'Regenhardt RW, Das AS, Stapleton CJ, Chandra RV, Rabinov JD, Patel AB, Hirsch JA, Leslie-Mazwi TM. Blood pressure and penumbral sustenance in stroke from large vessel occlusion. Front Neurol 2017;8:317. (Astrup\'s penumbra: infarction below about 10, viable for hours between 10 and 20 mL/100 g/min.)',
  'Sarraj A, Hassan AE, Abraham MG, et al. Trial of endovascular thrombectomy for large ischemic strokes (SELECT2). N Engl J Med 2023;388:1259–1271.',
  'Sciacca S, Lynch J, Davagnanam I, Barker R. Midbrain, pons, and medulla: anatomy and syndromes. Radiographics 2019;39:1110–1125. (General review of brainstem anatomy and syndromes.)',
  'Thomalla G, Simonsen CZ, Boutitie F, et al. MRI-guided thrombolysis for stroke with unknown time of onset (WAKE-UP). N Engl J Med 2018;379:611–622.',
  'Xiong Y, Campbell BCV, Schwamm LH, et al. Tenecteplase for ischemic stroke at 4.5 to 24 hours without thrombectomy (TRACE-III). N Engl J Med 2024;391:203–212.',
  'Yaghi S, Boehme AK, Dibu J, et al. Treatment and outcome of thrombolysis-related hemorrhage: a multicenter retrospective study. JAMA Neurol 2015;72:1451–1457. (Median 470 min from alteplase start to symptomatic haemorrhage; in-hospital mortality 52%.)',
  'Yaghi S, Eisenberger A, Willey JZ. Symptomatic intracerebral hemorrhage in acute ischemic stroke after thrombolysis with intravenous recombinant tissue plasminogen activator: a review of natural history and treatment. JAMA Neurol 2014;71:1181–1185.',
  'Yoshimura S, Sakai N, Yamagami H, et al. Endovascular therapy for acute stroke with a large ischemic region (RESCUE-Japan LIMIT). N Engl J Med 2022;386:1303–1313.',
  // ── common problems after stroke that the lesion site does not determine (postStrokeRisks.ts) ──
];

export const INSPIRATIONS: { name: string; licence: string; url: string; note: L }[] = [
  {
    name: 'openBF (INSIGNEO)',
    licence: 'Apache-2.0',
    url: 'https://github.com/INSIGNEO/openBF',
    note: { zh: '參考其 Alastruey 2007 Willis 環模型的血管半徑與長度；未複製程式碼。', en: 'Vessel radii/lengths of its Alastruey 2007 circle-of-Willis model used as reference; no code copied.' },
  },
  {
    name: 'WillisWorks',
    licence: 'GPL-3.0',
    url: 'https://github.com/abhogal-lab/WillisWorks',
    note: { zh: '啟發了自動調節、竊血與側枝的教學呈現方式；因授權不相容，只參考概念、未使用任何程式碼。', en: 'Inspired the teaching presentation of autoregulation, steal and collaterals; concepts only — no code used (licence incompatible).' },
  },
  {
    name: 'neuroaxis-atlas',
    licence: 'MIT',
    url: 'https://github.com/linkbag/neuroaxis-atlas',
    note: { zh: '參考其腦幹症候群卡片與資料來源標示方式。', en: 'Its brainstem syndrome cards and attribution practice informed ours.' },
  },
  {
    name: 'brain-game',
    licence: 'MIT (code)',
    url: 'https://github.com/Rickaym/brain-game',
    note: { zh: '參考其腦區—動脈對照與中風模擬的教學構想；其 3D 模型為 CC BY-SA 2.1 JP，本專案未使用。', en: 'Its region–artery mapping and stroke-simulator ideas informed ours; its 3D model (CC BY-SA 2.1 JP) is not used here.' },
  },
];
