/**
 * Arterial tree of the head & neck.
 *
 * Topology follows standard neurovascular anatomy (Osborn's Brain; Rhoton's Cranial Anatomy;
 * Tatu et al. 1996/1998 for territories). Centrelines are hand-authored waypoints in MNI152 2009c
 * space, then refined by `tools/build_assets.py` against the TemplateFlow template (cortical
 * branches are draped over the pial surface, cisternal segments are pushed out of parenchyma).
 *
 * Radii are typical adult lumen radii (mm). They are approximations for an educational model.
 * `n` = number of parallel vessels represented by one tube (perforator bundles).
 *
 * TODO(medical-review): radii, branch origins and collateral pairings are simplified.
 */

import type { VesselDef } from './types';

const bi = (v: Omit<VesselDef, 'bilateral'>): VesselDef => ({ ...v, bilateral: true });
const mid = (v: Omit<VesselDef, 'bilateral'>): VesselDef => ({ ...v, bilateral: false });

export const VESSEL_DEFS: VesselDef[] = [
  // ════════════════════════ Aortic arch & neck ════════════════════════
  mid({
    id: 'aortic_arch',
    name: { zh: '主動脈弓', en: 'Aortic arch' },
    abbr: 'Arch',
    desc: {
      zh: '心臟打出的血液經主動脈弓分出三條大血管供應頭頸部。心房顫動形成的血栓常從這裡被沖向腦部。',
      en: 'Blood from the heart passes the arch, which gives rise to the three great vessels of the head and neck. Cardiac emboli (e.g. from atrial fibrillation) travel from here to the brain.',
    },
    kind: 'trunk',
    group: 'extracranial',
    family: 'SUB',
    from: 'heart',
    to: 'arch',
    r: 13,
    path: [
      [16, 14, -214],
      [12, 10, -193],
      [6, 3, -182],
      [-2, -4, -178],
      [-10, -12, -181],
      [-16, -20, -193],
      [-18, -26, -214],
    ],
    pathMode: 'free',
    visualOnly: true,
    notOccludable: true,
  }),
  mid({
    id: 'brachiocephalic',
    name: { zh: '頭臂動脈幹', en: 'Brachiocephalic trunk' },
    abbr: 'BCT',
    desc: {
      zh: '主動脈弓第一條分支，再分成右鎖骨下動脈與右頸總動脈。',
      en: 'First branch of the arch; divides into the right subclavian and right common carotid arteries.',
    },
    kind: 'trunk',
    group: 'extracranial',
    family: 'SUB',
    from: 'arch',
    to: 'bct_bif',
    r: 5.5,
    path: [
      [6, 3, -181],
      [10, 5, -171],
      [14, 6, -160],
    ],
    pathMode: 'free',
  }),
  mid({
    id: 'subclavian_prox_r',
    name: { zh: '右鎖骨下動脈（近端）', en: 'Right subclavian artery (proximal)' },
    abbr: 'SubA',
    desc: {
      zh: '供應右手臂，並分出右椎動脈。',
      en: 'Supplies the right arm and gives off the right vertebral artery.',
    },
    kind: 'trunk',
    group: 'extracranial',
    family: 'SUB',
    from: 'bct_bif',
    to: 'sub_va_r',
    r: 4,
    path: [
      [14, 6, -160],
      [19, 3, -158],
      [23, -1, -157],
    ],
    pathMode: 'free',
  }),
  mid({
    id: 'subclavian_prox_l',
    name: { zh: '左鎖骨下動脈（近端）', en: 'Left subclavian artery (proximal)' },
    abbr: 'SubA',
    desc: {
      zh: '直接由主動脈弓分出。近端阻塞時，左手臂會從左椎動脈「偷」血——鎖骨下竊血。',
      en: 'Arises directly from the arch. If blocked proximally, the left arm "steals" blood backwards down the left vertebral artery — subclavian steal.',
    },
    kind: 'trunk',
    group: 'extracranial',
    family: 'SUB',
    from: 'arch',
    to: 'sub_va_l',
    r: 4,
    path: [
      [-9, -11, -180],
      [-15, -10, -170],
      [-20, -6, -161],
      [-23, -1, -157],
    ],
    pathMode: 'free',
  }),
  bi({
    id: 'subclavian_dist',
    name: { zh: '鎖骨下動脈（遠端，往手臂）', en: 'Subclavian artery (distal, to arm)' },
    abbr: 'Sub',
    desc: {
      zh: '椎動脈起點之後的鎖骨下動脈，繼續成為腋動脈供應手臂。',
      en: 'The subclavian beyond the vertebral origin, continuing as the axillary artery to the arm.',
    },
    kind: 'trunk',
    group: 'extracranial',
    family: 'SUB',
    from: 'sub_va_{s}',
    to: 'arm_{s}',
    r: 3.8,
    path: [
      [23, -1, -157],
      [36, -4, -160],
      [50, -6, -166],
      [64, -8, -174],
    ],
    pathMode: 'free',
  }),
  mid({
    id: 'cca_r',
    name: { zh: '右頸總動脈', en: 'Right common carotid artery' },
    abbr: 'CCA',
    desc: {
      zh: '在頸部（約甲狀軟骨高度）分成內頸動脈與外頸動脈。',
      en: 'Divides in the neck (around the thyroid cartilage) into internal and external carotids.',
    },
    kind: 'trunk',
    group: 'extracranial',
    family: 'ICA',
    from: 'bct_bif',
    to: 'cca_bif_r',
    r: 3.3,
    path: [
      [14, 6, -160],
      [18, 8, -145],
      [22, 8, -128],
      [24, 6, -112],
    ],
    pathMode: 'free',
  }),
  mid({
    id: 'cca_l',
    name: { zh: '左頸總動脈', en: 'Left common carotid artery' },
    abbr: 'CCA',
    desc: {
      zh: '直接由主動脈弓分出，在頸部分成內、外頸動脈。',
      en: 'Arises directly from the arch and divides in the neck into internal and external carotids.',
    },
    kind: 'trunk',
    group: 'extracranial',
    family: 'ICA',
    from: 'arch',
    to: 'cca_bif_l',
    r: 3.3,
    path: [
      [-1, -3, -179],
      [-8, 2, -165],
      [-16, 6, -148],
      [-21, 8, -130],
      [-24, 6, -112],
    ],
    pathMode: 'free',
  }),
  bi({
    id: 'ica_cervical',
    name: { zh: '內頸動脈頸段', en: 'Internal carotid artery, cervical segment' },
    abbr: 'ICA C1',
    desc: {
      zh: '頸動脈分叉處是動脈粥狀硬化斑塊最好發的位置；斑塊破裂形成的栓子會隨血流進入同側大腦（動脈對動脈栓塞）。',
      en: 'The carotid bifurcation is the commonest site of atherosclerotic plaque; fragments embolise into the same-side hemisphere (artery-to-artery embolism).',
    },
    kind: 'trunk',
    group: 'extracranial',
    family: 'ICA',
    from: 'cca_bif_{s}',
    to: 'ica_skull_{s}',
    parent: 'cca_{s}',
    r: 2.5,
    path: [
      [24, 6, -112],
      [26, 2, -100],
      [28, -4, -86],
      [27, -8, -74],
      [26, -11, -64],
    ],
    pathMode: 'free',
  }),
  bi({
    id: 'eca',
    name: { zh: '外頸動脈', en: 'External carotid artery' },
    abbr: 'ECA',
    desc: {
      zh: '供應臉部與頭皮。內頸動脈阻塞時，可經眼動脈逆流提供側枝循環。',
      en: 'Supplies the face and scalp. When the ICA is blocked it can feed the brain backwards through the ophthalmic artery.',
    },
    kind: 'trunk',
    group: 'extracranial',
    family: 'ECA',
    from: 'cca_bif_{s}',
    to: 'eca_div_{s}',
    parent: 'cca_{s}',
    r: 2.0,
    path: [
      [24, 6, -112],
      [25, 11, -104],
      [27, 15, -94],
      [29, 16, -86],
    ],
    pathMode: 'free',
  }),
  bi({
    id: 'eca_facial',
    name: { zh: '顏面動脈', en: 'Facial artery' },
    desc: {
      zh: '繞過下顎到臉部，終支角動脈在內眼角與眼動脈吻合。',
      en: 'Crosses the mandible to the face; its angular branch anastomoses with the ophthalmic artery at the inner canthus.',
    },
    kind: 'branch',
    group: 'extracranial',
    family: 'ECA',
    from: 'eca_{s}@mid',
    to: 'facial_end_{s}',
    parent: 'eca_{s}',
    r: 1.1,
    path: [
      [25.5, 12, -100],
      [34, 30, -104],
      [42, 50, -92],
      [38, 64, -70],
      [26, 66, -50],
      [18, 60, -40],
    ],
    pathMode: 'free',
  }),
  bi({
    id: 'eca_sta',
    name: { zh: '顳淺動脈', en: 'Superficial temporal artery' },
    desc: {
      zh: '耳前可摸到脈搏的頭皮動脈；外科做顱內外繞道手術（STA–MCA bypass）時使用。',
      en: 'The scalp artery pulsating in front of the ear; used as the donor in STA–MCA bypass surgery.',
    },
    kind: 'branch',
    group: 'extracranial',
    family: 'ECA',
    from: 'eca_div_{s}',
    to: 'sta_end_{s}',
    parent: 'eca_{s}',
    r: 1.1,
    path: [
      [29, 16, -86],
      [44, 10, -72],
      [60, 6, -56],
      [73, 6, -32],
      [78, 10, 0],
      [72, 26, 32],
    ],
    pathMode: 'free',
  }),
  bi({
    id: 'eca_maxillary',
    name: { zh: '上頜動脈與中腦膜動脈', en: 'Maxillary & middle meningeal arteries' },
    desc: {
      zh: '中腦膜動脈供應硬腦膜（不是腦組織本身），在眼眶附近與眼動脈有吻合。',
      en: 'The middle meningeal artery supplies the dura (not the brain itself) and anastomoses with the ophthalmic artery near the orbit.',
    },
    kind: 'branch',
    group: 'extracranial',
    family: 'ECA',
    from: 'eca_div_{s}',
    to: 'mma_end_{s}',
    parent: 'eca_{s}',
    r: 1.0,
    path: [
      [29, 16, -86],
      [36, 20, -74],
      [34, 10, -60],
      [52, 4, -46],
      [74, 0, -24],
      [78, -4, 6],
      [73, -8, 40],
    ],
    pathMode: 'free',
  }),
  bi({
    id: 'eca_occipital',
    name: { zh: '枕動脈', en: 'Occipital artery' },
    desc: {
      zh: '供應後頭皮，與椎動脈的肌支相吻合。',
      en: 'Supplies the posterior scalp and anastomoses with muscular branches of the vertebral artery.',
    },
    kind: 'branch',
    group: 'extracranial',
    family: 'ECA',
    from: 'eca_{s}@mid',
    to: 'occ_end_{s}',
    parent: 'eca_{s}',
    r: 1.0,
    path: [
      [25.5, 12, -100],
      [32, -8, -98],
      [40, -36, -92],
      [40, -64, -84],
      [33, -92, -64],
      [22, -110, -40],
    ],
    pathMode: 'free',
  }),
  bi({
    id: 'va_extracranial',
    name: { zh: '椎動脈（頸段 V1–V3）', en: 'Vertebral artery, extracranial (V1–V3)' },
    abbr: 'VA',
    desc: {
      zh: '從鎖骨下動脈往上穿過頸椎橫突孔，在寰椎處繞一個彎後進入顱內。頸部扭傷可造成剝離。',
      en: 'Ascends from the subclavian through the cervical transverse foramina and loops around the atlas before entering the skull. Neck trauma can dissect it.',
    },
    kind: 'trunk',
    group: 'extracranial',
    family: 'VA',
    from: 'sub_va_{s}',
    to: 'va_dura_{s}',
    r: 1.5,
    path: [
      [23, -1, -157],
      [25, -8, -142],
      [27, -14, -122],
      [28, -19, -102],
      [29, -24, -88],
      [31, -33, -81],
      [26, -43, -78],
      [18, -46, -75],
      [12.5, -44, -73],
    ],
    pathMode: 'free',
  }),

  // ════════════════════════ Internal carotid (intracranial) ════════════════════════
  bi({
    id: 'ica_petrous_cavernous',
    name: { zh: '內頸動脈岩骨段與海綿竇段（虹吸部）', en: 'ICA petrous & cavernous segments (siphon)' },
    abbr: 'ICA C2–C5',
    desc: {
      zh: '穿過顱底骨頭後，在海綿竇內形成 S 形彎曲（頸動脈虹吸）。',
      en: 'Passes through the skull base and forms the S-shaped carotid siphon within the cavernous sinus.',
    },
    kind: 'trunk',
    group: 'anterior',
    family: 'ICA',
    from: 'ica_skull_{s}',
    to: 'ica_ophth_{s}',
    parent: 'ica_cervical_{s}',
    r: 2.2,
    path: [
      [26, -11, -64],
      [23, -6, -55],
      [19, 1, -47],
      [16.5, 3, -41],
      [15.5, 3, -36],
      [15, 9, -35],
      [14.5, 14, -31],
      [14, 12, -26.5],
      [14, 8, -23.5],
    ],
    pathMode: 'free',
  }),
  bi({
    id: 'ophthalmic',
    name: { zh: '眼動脈', en: 'Ophthalmic artery' },
    abbr: 'OA',
    desc: {
      zh: '內頸動脈進入顱內後第一條大分支，其分支視網膜中央動脈供應視網膜。頸動脈的小栓子常先卡在這裡，造成一過性單眼失明。',
      en: 'First major intradural ICA branch; its central retinal artery supplies the retina. Small carotid emboli often lodge here, causing transient monocular blindness.',
    },
    kind: 'branch',
    group: 'anterior',
    family: 'OPH',
    from: 'ica_ophth_{s}',
    to: 'ophth_end_{s}',
    parent: 'ica_petrous_cavernous_{s}',
    r: 0.75,
    path: [
      [14, 8, -23.5],
      [17, 16, -26],
      [21, 28, -30],
      [26, 40, -34],
      [30, 49, -36],
    ],
    pathMode: 'free',
  }),
  bi({
    id: 'ica_ophthalmic_seg',
    name: { zh: '內頸動脈眼段（床突上段）', en: 'ICA ophthalmic (supraclinoid) segment' },
    abbr: 'ICA C6',
    desc: {
      zh: '眼動脈起點到後交通動脈起點之間；此處也是動脈瘤好發位置。',
      en: 'Between the ophthalmic and posterior communicating origins; a common aneurysm site.',
    },
    kind: 'trunk',
    group: 'anterior',
    family: 'ICA',
    from: 'ica_ophth_{s}',
    to: 'ica_pcomm_{s}',
    parent: 'ica_petrous_cavernous_{s}',
    r: 2.0,
    path: [
      [14, 8, -23.5],
      [14.5, 4.5, -21.5],
      [15, 1, -20],
    ],
    pathMode: 'cistern',
  }),
  bi({
    id: 'ica_terminal',
    name: { zh: '內頸動脈末端（交通段）', en: 'ICA terminal (communicating) segment' },
    abbr: 'ICA-T',
    desc: {
      zh: '分出前脈絡叢動脈後分叉為前、中大腦動脈。大型心因性栓子卡在此處（T 型阻塞）會同時阻斷前、中大腦動脈，預後很差。',
      en: 'Gives off the anterior choroidal artery then bifurcates into ACA and MCA. A large cardiac embolus lodged here ("carotid-T") blocks both ACA and MCA and carries a poor prognosis.',
    },
    kind: 'trunk',
    group: 'anterior',
    family: 'ICA',
    from: 'ica_pcomm_{s}',
    to: 'ica_term_{s}',
    parent: 'ica_ophthalmic_seg_{s}',
    r: 1.9,
    path: [
      [15, 1, -20],
      [15.5, 0.5, -17.5],
      [16, 1.5, -15.5],
    ],
    pathMode: 'cistern',
    occludesDistalJunction: true,
  }),
  bi({
    id: 'acha',
    name: { zh: '前脈絡叢動脈', en: 'Anterior choroidal artery' },
    abbr: 'AChA',
    desc: {
      zh: '細小但重要：供應內囊後肢下部、視徑、外側膝狀體、海馬迴前部與部分大腦腳。阻塞可造成對側偏癱、半身感覺喪失與偏盲。',
      en: 'Small but critical: supplies the lower posterior limb of the internal capsule, optic tract, lateral geniculate body, anterior hippocampus and part of the cerebral peduncle. Occlusion gives hemiplegia, hemisensory loss and hemianopia.',
    },
    kind: 'perforator',
    group: 'anterior',
    family: 'AChA',
    from: 'ica_terminal_{s}@mid',
    to: 'acha_end_{s}',
    parent: 'ica_terminal_{s}',
    r: 0.5,
    n: 2,
    path: [
      [15.5, 0.5, -17.5],
      [19, -5, -17.5],
      [22, -11, -16.5],
      [25, -17, -14],
      [28, -23, -11],
    ],
    pathMode: 'cistern',
  }),

  // ════════════════════════ Anterior cerebral artery ════════════════════════
  bi({
    id: 'aca_a1',
    name: { zh: '前大腦動脈 A1 段', en: 'Anterior cerebral artery, A1 segment' },
    abbr: 'A1',
    desc: {
      zh: '從內頸動脈末端往內前方到前交通動脈，是 Willis 環的前半部。約 10% 的人一側 A1 發育不良。',
      en: 'Runs medially to the anterior communicating artery, forming the front of the circle of Willis. About 10% of people have a hypoplastic A1 on one side.',
    },
    kind: 'trunk',
    group: 'willis',
    family: 'ACA',
    from: 'ica_term_{s}',
    to: 'aca_acomm_{s}',
    parent: 'ica_terminal_{s}',
    r: 1.15,
    path: [
      [16, 1.5, -15.5],
      [12, 6, -16],
      [7, 11, -15.5],
      [2.2, 14.5, -13],
    ],
    pathMode: 'cistern',
  }),
  mid({
    id: 'acomm',
    name: { zh: '前交通動脈', en: 'Anterior communicating artery' },
    abbr: 'AComm',
    desc: {
      zh: '連接左右前大腦動脈的短血管。一側內頸動脈阻塞時，對側血流可經此跨過中線支援——最重要的側枝通道之一。也是腦動脈瘤最常見的位置。',
      en: 'Short vessel joining the two ACAs. When one ICA is blocked, blood crosses the midline here — one of the most important collateral routes. Also the commonest aneurysm site.',
    },
    kind: 'communicating',
    group: 'willis',
    family: 'ACA',
    from: 'aca_acomm_r',
    to: 'aca_acomm_l',
    r: 0.75,
    path: [
      [2.2, 14.5, -13],
      [0, 15, -13],
      [-2.2, 14.5, -13],
    ],
    pathMode: 'cistern',
  }),
  bi({
    id: 'heubner',
    name: { zh: '赫布納返動脈', en: 'Recurrent artery of Heubner' },
    desc: {
      zh: '從 A1/A2 交界往回走的穿通動脈，供應尾狀核頭、內囊前肢與殼核前部。',
      en: 'Perforator that doubles back from the A1/A2 junction to the caudate head, anterior limb of the internal capsule and anterior putamen.',
    },
    kind: 'perforator',
    group: 'anterior',
    family: 'ACA',
    from: 'aca_acomm_{s}',
    to: 'heubner_end_{s}',
    parent: 'aca_a1_{s}',
    r: 0.35,
    n: 2,
    path: [
      [2.2, 14.5, -13],
      [7, 13.5, -15],
      [13, 10, -15],
      [16, 9, -9],
      [15, 11, -1],
      [13, 13, 6],
    ],
    pathMode: 'deep',
  }),
  bi({
    id: 'aca_a2',
    name: { zh: '前大腦動脈 A2 段', en: 'Anterior cerebral artery, A2 segment' },
    abbr: 'A2',
    desc: {
      zh: '前交通動脈之後沿大腦縱裂往上，繞過胼胝體膝部。',
      en: 'Ascends in the interhemispheric fissure beyond the AComm and curves around the genu of the corpus callosum.',
    },
    kind: 'trunk',
    group: 'anterior',
    family: 'ACA',
    from: 'aca_acomm_{s}',
    to: 'aca_a2_end_{s}',
    parent: 'aca_a1_{s}',
    r: 1.1,
    path: [
      [2.2, 14.5, -13],
      [2.8, 20, -8],
      [3, 28, -2],
      [3, 35, 5],
      [3, 38, 13],
    ],
    pathMode: 'cistern',
  }),
  bi({
    id: 'aca_frontopolar',
    name: { zh: '眼眶額動脈與額極動脈', en: 'Orbitofrontal & frontopolar arteries' },
    desc: {
      zh: '供應直回、內側眼眶額葉與額極。',
      en: 'Supply the gyrus rectus, medial orbitofrontal cortex and frontal pole.',
    },
    kind: 'branch',
    group: 'anterior',
    family: 'ACA',
    from: 'aca_a2_{s}@mid',
    to: 'aca_fp_end_{s}',
    parent: 'aca_a2_{s}',
    r: 0.6,
    path: [
      [3, 28, -2],
      [4, 36, -12],
      [5, 48, -15],
      [6, 58, -8],
      [7, 65, 6],
    ],
    pathMode: 'surface',
  }),
  bi({
    id: 'aca_callosomarginal',
    name: { zh: '胼胝體緣動脈', en: 'Callosomarginal artery' },
    desc: {
      zh: '沿扣帶溝走，供應內側額葉、輔助運動區與扣帶迴前部。',
      en: 'Runs in the cingulate sulcus to the medial frontal lobe, supplementary motor area and anterior cingulate.',
    },
    kind: 'branch',
    group: 'anterior',
    family: 'ACA',
    from: 'aca_a2_end_{s}',
    to: 'aca_cm_end_{s}',
    parent: 'aca_a2_{s}',
    r: 0.8,
    path: [
      [3, 38, 13],
      [4, 44, 26],
      [4, 38, 40],
      [5, 24, 52],
      [5, 6, 60],
      [5, -10, 64],
    ],
    pathMode: 'surface',
  }),
  bi({
    id: 'aca_pericallosal',
    name: { zh: '胼胝體周動脈', en: 'Pericallosal artery' },
    desc: {
      zh: '沿胼胝體上方往後，供應胼胝體與楔前葉，末端與後大腦動脈的胼胝體壓部支吻合。',
      en: 'Runs back over the corpus callosum, supplying it and the precuneus; ends anastomosing with the splenial branch of the PCA.',
    },
    kind: 'branch',
    group: 'anterior',
    family: 'ACA',
    from: 'aca_a2_end_{s}',
    to: 'aca_pc_end_{s}',
    parent: 'aca_a2_{s}',
    r: 0.8,
    path: [
      [3, 38, 13],
      [3, 32, 24],
      [3, 20, 30],
      [3, 5, 32],
      [3, -10, 32],
      [3, -25, 31],
      [3, -38, 27],
    ],
    pathMode: 'surface',
  }),
  bi({
    id: 'aca_paracentral',
    name: { zh: '旁中央動脈', en: 'Paracentral artery' },
    desc: {
      zh: '供應旁中央小葉——控制對側腿部運動與感覺的皮質，也參與排尿控制。前大腦動脈中風「腿比手嚴重」就是因為它。',
      en: 'Supplies the paracentral lobule — the cortex for the opposite leg and bladder control. This is why ACA strokes affect the leg more than the arm.',
    },
    kind: 'branch',
    group: 'anterior',
    family: 'ACA',
    from: 'aca_pericallosal_{s}@mid',
    to: 'aca_para_end_{s}',
    parent: 'aca_pericallosal_{s}',
    r: 0.55,
    path: [
      [3, 2, 32],
      [4, -8, 42],
      [5, -18, 56],
      [5, -26, 66],
      [7, -32, 74],
    ],
    pathMode: 'surface',
  }),

  // ════════════════════════ Middle cerebral artery ════════════════════════
  bi({
    id: 'mca_m1',
    name: { zh: '中大腦動脈 M1 段', en: 'Middle cerebral artery, M1 segment' },
    abbr: 'M1',
    desc: {
      zh: '最常被栓子塞住的腦血管（約承接 60–80% 的內頸動脈血流）。M1 近端阻塞會同時切斷豆紋動脈（深部）與整個大腦外側皮質。',
      en: 'The artery most often hit by emboli (it takes most ICA flow). Proximal M1 occlusion cuts off both the lenticulostriate perforators (deep) and the whole lateral cortex.',
    },
    kind: 'trunk',
    group: 'anterior',
    family: 'MCA',
    from: 'ica_term_{s}',
    to: 'mca_bif_{s}',
    parent: 'ica_terminal_{s}',
    r: 1.4,
    path: [
      [16, 1.5, -15.5],
      [21, 2.5, -16.5],
      [27, 3.5, -15.5],
      [33, 4.5, -12],
    ],
    pathMode: 'cistern',
  }),
  bi({
    id: 'lenticulostriate',
    name: { zh: '豆紋動脈（外側）', en: 'Lateral lenticulostriate arteries' },
    abbr: 'LSA',
    desc: {
      zh: '一群細小的「終末動脈」，沒有側枝可以救援。供應殼核、蒼白球外側與內囊。高血壓造成的小血管病變（腔隙性中風、腦出血）好發於此。',
      en: 'A fan of small end-arteries with no collateral backup, supplying the putamen, lateral pallidum and internal capsule. Typical site of hypertensive small-vessel disease (lacunes, haemorrhage).',
    },
    kind: 'perforator',
    group: 'anterior',
    family: 'LSA',
    from: 'mca_m1_{s}@mid',
    to: 'lsa_end_{s}',
    parent: 'mca_m1_{s}',
    r: 0.3,
    n: 8,
    path: [
      [24, 3, -16],
      [24, 4, -8],
      [24, 4, 0],
      [23, 2, 9],
      [22, -2, 17],
    ],
    pathMode: 'deep',
  }),
  bi({
    id: 'mca_temporal_anterior',
    name: { zh: '顳前動脈', en: 'Anterior temporal artery' },
    desc: { zh: '由 M1 分出，供應顳極。', en: 'Early M1 branch to the temporal pole.' },
    kind: 'branch',
    group: 'anterior',
    family: 'MCA',
    from: 'mca_m1_{s}@mid',
    to: 'mca_ta_end_{s}',
    parent: 'mca_m1_{s}',
    r: 0.6,
    path: [
      [24, 3, -16],
      [31, 8, -24],
      [37, 11, -32],
      [43, 9, -36],
    ],
    pathMode: 'surface',
    surfaceFrom: 0.3,
  }),
  bi({
    id: 'mca_m2_sup',
    name: { zh: '中大腦動脈上分支（M2）', en: 'MCA superior division (M2)' },
    abbr: 'M2 sup',
    desc: {
      zh: '沿島葉往上，供應額葉外側、運動與感覺皮質的臉手區。左側受損常造成表達性失語與右側臉手無力。',
      en: 'Runs up over the insula to the lateral frontal lobe and the face/arm motor–sensory cortex. On the left, occlusion gives expressive aphasia and right face/arm weakness.',
    },
    kind: 'trunk',
    group: 'anterior',
    family: 'MCA',
    from: 'mca_bif_{s}',
    to: 'mca_sup_end_{s}',
    parent: 'mca_m1_{s}',
    r: 1.1,
    path: [
      [33, 4.5, -12],
      [36, 8, -4],
      [37.5, 8, 5],
      [38.5, 4, 13],
    ],
    pathMode: 'deep',
  }),
  bi({
    id: 'mca_m2_inf',
    name: { zh: '中大腦動脈下分支（M2）', en: 'MCA inferior division (M2)' },
    abbr: 'M2 inf',
    desc: {
      zh: '供應顳葉與頂葉後部。左側受損常造成接受性失語；右側則常見半側忽略。',
      en: 'Supplies the temporal and posterior parietal lobes. Left-sided occlusion gives receptive aphasia; right-sided gives neglect.',
    },
    kind: 'trunk',
    group: 'anterior',
    family: 'MCA',
    from: 'mca_bif_{s}',
    to: 'mca_inf_end_{s}',
    parent: 'mca_m1_{s}',
    r: 1.1,
    path: [
      [33, 4.5, -12],
      [37.5, -2, -7],
      [39.5, -12, -3],
      [40.5, -22, 4],
    ],
    pathMode: 'deep',
  }),
  bi({
    id: 'mca_orbitofrontal',
    name: { zh: '外側眼眶額動脈', en: 'Lateral orbitofrontal artery' },
    desc: { zh: '供應外側眼眶額葉。', en: 'Supplies the lateral orbitofrontal cortex.' },
    kind: 'branch',
    group: 'anterior',
    family: 'MCA',
    from: 'mca_m2_sup_{s}@mid',
    to: 'mca_of_end_{s}',
    parent: 'mca_m2_sup_{s}',
    r: 0.6,
    path: [
      [37, 7.5, 1],
      [36, 18, -10],
      [37, 30, -14],
      [38, 42, -12],
      [36, 52, -6],
    ],
    pathMode: 'surface',
    surfaceFrom: 0.25,
  }),
  bi({
    id: 'mca_prefrontal',
    name: { zh: '前額動脈（燭台動脈）', en: 'Prefrontal (candelabra) artery' },
    desc: {
      zh: '供應額中迴、額下迴（左側為布洛卡區）與額葉眼動區。',
      en: "Supplies the middle and inferior frontal gyri (Broca's area on the left) and the frontal eye field.",
    },
    kind: 'branch',
    group: 'anterior',
    family: 'MCA',
    from: 'mca_sup_end_{s}',
    to: 'mca_pf_end_{s}',
    parent: 'mca_m2_sup_{s}',
    r: 0.7,
    path: [
      [38.5, 4, 13],
      [46, 15, 14],
      [52, 26, 20],
      [48, 38, 28],
      [40, 50, 32],
    ],
    pathMode: 'surface',
    surfaceFrom: 0.25,
  }),
  bi({
    id: 'mca_precentral',
    name: { zh: '中央前動脈', en: 'Precentral artery' },
    desc: {
      zh: '供應中央前迴下 2/3——控制對側臉、舌、手與手臂的運動皮質。',
      en: 'Supplies the lower two-thirds of the precentral gyrus — motor cortex for the opposite face, tongue, hand and arm.',
    },
    kind: 'branch',
    group: 'anterior',
    family: 'MCA',
    from: 'mca_sup_end_{s}',
    to: 'mca_prc_end_{s}',
    parent: 'mca_m2_sup_{s}',
    r: 0.7,
    path: [
      [38.5, 4, 13],
      [50, 5, 20],
      [57, 0, 30],
      [52, -7, 45],
      [42, -13, 58],
    ],
    pathMode: 'surface',
    surfaceFrom: 0.2,
  }),
  bi({
    id: 'mca_central',
    name: { zh: '中央動脈（羅蘭多動脈）', en: 'Central (Rolandic) artery' },
    desc: {
      zh: '沿中央溝走，供應中央後迴的臉手感覺區。',
      en: 'Runs along the central sulcus, supplying the face/arm sensory cortex of the postcentral gyrus.',
    },
    kind: 'branch',
    group: 'anterior',
    family: 'MCA',
    from: 'mca_sup_end_{s}',
    to: 'mca_cen_end_{s}',
    parent: 'mca_m2_sup_{s}',
    r: 0.7,
    path: [
      [38.5, 4, 13],
      [50, -8, 22],
      [58, -16, 32],
      [52, -23, 48],
      [44, -28, 60],
    ],
    pathMode: 'surface',
    surfaceFrom: 0.2,
  }),
  bi({
    id: 'mca_ant_parietal',
    name: { zh: '頂前動脈', en: 'Anterior parietal artery' },
    desc: {
      zh: '供應緣上迴（左側與語言複誦、動作計畫有關）。',
      en: 'Supplies the supramarginal gyrus (on the left: repetition and praxis).',
    },
    kind: 'branch',
    group: 'anterior',
    family: 'MCA',
    from: 'mca_sup_end_{s}',
    to: 'mca_ap_end_{s}',
    parent: 'mca_m2_sup_{s}',
    r: 0.65,
    path: [
      [38.5, 4, 13],
      [48, -18, 22],
      [57, -32, 32],
      [52, -40, 46],
      [44, -47, 57],
    ],
    pathMode: 'surface',
    surfaceFrom: 0.2,
  }),
  bi({
    id: 'mca_post_parietal',
    name: { zh: '頂後動脈', en: 'Posterior parietal artery' },
    desc: { zh: '供應頂上小葉外側。', en: 'Supplies the lateral superior parietal lobule.' },
    kind: 'branch',
    group: 'anterior',
    family: 'MCA',
    from: 'mca_inf_end_{s}',
    to: 'mca_pp_end_{s}',
    parent: 'mca_m2_inf_{s}',
    r: 0.65,
    path: [
      [40.5, -22, 4],
      [48, -34, 18],
      [50, -46, 36],
      [43, -55, 54],
    ],
    pathMode: 'surface',
    surfaceFrom: 0.25,
  }),
  bi({
    id: 'mca_angular',
    name: { zh: '角迴動脈', en: 'Angular artery' },
    desc: {
      zh: '供應角迴：左側與閱讀、書寫、計算有關（Gerstmann 症候群）；右側與空間注意力有關。',
      en: 'Supplies the angular gyrus: on the left reading, writing and calculation (Gerstmann syndrome); on the right spatial attention.',
    },
    kind: 'branch',
    group: 'anterior',
    family: 'MCA',
    from: 'mca_inf_end_{s}',
    to: 'mca_ang_end_{s}',
    parent: 'mca_m2_inf_{s}',
    r: 0.65,
    path: [
      [40.5, -22, 4],
      [50, -40, 14],
      [51, -56, 26],
      [45, -66, 37],
    ],
    pathMode: 'surface',
    surfaceFrom: 0.25,
  }),
  bi({
    id: 'mca_temporooccipital',
    name: { zh: '顳枕動脈', en: 'Temporo-occipital artery' },
    desc: {
      zh: '往後供應顳枕交界與外側枕葉，並提供枕極（中心視力區）的側枝血流。',
      en: 'Runs back to the temporo-occipital junction and lateral occipital cortex, and provides collateral supply to the occipital pole (central vision).',
    },
    kind: 'branch',
    group: 'anterior',
    family: 'MCA',
    from: 'mca_inf_end_{s}',
    to: 'mca_to_end_{s}',
    parent: 'mca_m2_inf_{s}',
    r: 0.6,
    path: [
      [40.5, -22, 4],
      [54, -40, 4],
      [55, -56, 1],
      [47, -72, 0],
      [38, -88, 2],
    ],
    pathMode: 'surface',
    surfaceFrom: 0.2,
  }),
  bi({
    id: 'mca_temporal_posterior',
    name: { zh: '顳後動脈', en: 'Posterior temporal artery' },
    desc: {
      zh: '供應顳上迴後部（左側為韋尼克區——理解語言的中樞）。',
      en: "Supplies the posterior superior temporal gyrus (Wernicke's area on the left — language comprehension).",
    },
    kind: 'branch',
    group: 'anterior',
    family: 'MCA',
    from: 'mca_inf_end_{s}',
    to: 'mca_tp_end_{s}',
    parent: 'mca_m2_inf_{s}',
    r: 0.65,
    path: [
      [40.5, -22, 4],
      [56, -30, 5],
      [61, -40, 10],
      [60, -50, 16],
    ],
    pathMode: 'surface',
    surfaceFrom: 0.2,
  }),
  bi({
    id: 'mca_temporal_middle',
    name: { zh: '顳中動脈', en: 'Middle temporal artery' },
    desc: {
      zh: '供應顳上迴與顳中迴中段（聽覺聯合區）。',
      en: 'Supplies the middle portions of the superior and middle temporal gyri (auditory association cortex).',
    },
    kind: 'branch',
    group: 'anterior',
    family: 'MCA',
    from: 'mca_m2_inf_{s}@mid',
    to: 'mca_tm_end_{s}',
    parent: 'mca_m2_inf_{s}',
    r: 0.6,
    path: [
      [39.5, -12, -3],
      [54, -12, -6],
      [62, -22, -10],
      [63, -36, -12],
    ],
    pathMode: 'surface',
    surfaceFrom: 0.25,
  }),

  // ════════════════════════ Posterior communicating & PCA ════════════════════════
  bi({
    id: 'pcomm',
    name: { zh: '後交通動脈', en: 'Posterior communicating artery' },
    abbr: 'PComm',
    desc: {
      zh: '連接前（內頸動脈）與後（椎基底）循環。粗細個體差異很大；MRA 研究中每一側都有一半以上的人缺如或極細（< 1 mm），影響阻塞後的代償能力。',
      en: 'Joins the anterior (carotid) and posterior (vertebrobasilar) circulations. Its size varies greatly — on MRA it is missing or under 1 mm on each side in more than half of people — which changes how well a blockage is compensated.',
    },
    kind: 'communicating',
    group: 'willis',
    family: 'ICA',
    from: 'ica_pcomm_{s}',
    to: 'pca_pcomm_{s}',
    parent: 'ica_ophthalmic_seg_{s}',
    r: 0.7,
    path: [
      [15, 1, -20],
      [14, -4, -20],
      [12, -9, -19.5],
      [10, -14, -18.5],
    ],
    pathMode: 'cistern',
  }),
  bi({
    // persistent trigeminal artery: Huang W et al. Surg Radiol Anat 2023;45:947–957 (57 of 94,487
    // on CTA/MRA, 0.06 %; lateral course in 89.5 %; basilar artery non-dominant in most);
    // Triantafyllou G et al. Neuroradiology 2026;68:1607–1617 (pooled prevalence 0.20 %)
    id: 'trigeminal_persistent',
    name: { zh: '永存三叉動脈', en: 'Persistent trigeminal artery' },
    abbr: 'PTA',
    desc: {
      zh: '胚胎時期連接內頸動脈與基底動脈的血管，通常在出生前消失，少數人（約 0.06–0.2%）一直保留。它從海綿竇段內頸動脈發出，在小腦上動脈與小腦前下動脈之間接上基底動脈；這時接點以下的基底動脈多半較細。頸動脈的栓子可經由它到達腦幹與小腦。只有在選了這個變異時才存在。',
      en: 'An embryonic connection between the internal carotid and basilar arteries that normally disappears before birth and persists in about 0.06–0.2% of people. It leaves the cavernous ICA and joins the basilar artery between the superior and anterior inferior cerebellar arteries; the basilar artery below the junction is then usually small. Carotid emboli can reach the brainstem and cerebellum through it. Present only when this variant is chosen.',
    },
    kind: 'communicating',
    group: 'willis',
    family: 'ICA',
    from: 'ica_petrous_cavernous_{s}@mid',
    to: 'ba_rostral',
    parent: 'ica_petrous_cavernous_{s}',
    r: 1.3,
    path: [
      [16.69, 2.87, -41.61],
      [15, -1.5, -41.5],
      [12, -6, -40],
      [8, -9, -38],
      [4, -10.8, -36.2],
      [1.2, -11.4, -35.2],
    ],
    pathMode: 'free',
    variantOnly: true,
  }),
  bi({
    id: 'tuberothalamic',
    name: { zh: '結節視丘動脈（極動脈）', en: 'Tuberothalamic (polar) artery' },
    desc: {
      zh: '由後交通動脈分出，供應視丘前部。受損會出現記憶與個性改變。',
      en: 'Arises from the PComm and supplies the anterior thalamus; lesions cause memory and personality change.',
    },
    kind: 'perforator',
    group: 'willis',
    family: 'THAL',
    from: 'pcomm_{s}@mid',
    to: 'tuberothal_end_{s}',
    parent: 'pcomm_{s}',
    r: 0.3,
    path: [
      [12.5, -6.5, -19.8],
      [10, -6, -10],
      [8, -7, 0],
      [7, -8, 8],
    ],
    pathMode: 'deep',
  }),

  // ════════════════════════ Vertebrobasilar system ════════════════════════
  bi({
    id: 'va_v4_prox',
    name: { zh: '椎動脈顱內段（V4 近端）', en: 'Vertebral artery V4 (proximal)' },
    abbr: 'V4',
    desc: {
      zh: '進入顱內後，沿延髓外側往前走，分出小腦後下動脈（PICA）。',
      en: 'After entering the skull it curves around the medulla and gives off the posterior inferior cerebellar artery (PICA).',
    },
    kind: 'trunk',
    group: 'posterior',
    family: 'VA',
    from: 'va_dura_{s}',
    to: 'va_pica_{s}',
    parent: 'va_extracranial_{s}',
    r: 1.4,
    path: [
      [12.5, -44, -73],
      [11.5, -40, -69],
      [10.5, -36, -65],
      [9, -33, -62],
    ],
    pathMode: 'cistern',
  }),
  bi({
    id: 'va_v4_dist',
    name: { zh: '椎動脈顱內段（V4 遠端）', en: 'Vertebral artery V4 (distal)' },
    abbr: 'V4',
    desc: {
      zh: 'PICA 起點之後到匯合成基底動脈；沿途分出供應延髓外側與內側的穿通支。此段阻塞是華倫堡氏症候群最常見的原因。',
      en: 'From the PICA origin to the basilar confluence, giving perforators to the lateral and medial medulla. Occlusion here is the commonest cause of Wallenberg syndrome.',
    },
    kind: 'trunk',
    group: 'posterior',
    family: 'VA',
    from: 'va_pica_{s}',
    to: 'vb_conf',
    parent: 'va_v4_prox_{s}',
    r: 1.4,
    path: [
      [9, -33, -62],
      [7, -29, -58],
      [4.5, -25, -54],
      [2.2, -21.5, -51],
      [0.6, -19.5, -49],
    ],
    pathMode: 'cistern',
  }),
  bi({
    id: 'lat_medullary_perf',
    name: { zh: '延髓外側穿通支', en: 'Lateral medullary perforators' },
    desc: {
      zh: '由椎動脈遠端分出，供應延髓外側（吞嚥、聲音、臉部與身體痛溫覺、平衡、交感神經）。',
      en: 'From the distal vertebral artery to the lateral medulla (swallowing, voice, pain/temperature pathways, balance, sympathetic fibres).',
    },
    kind: 'perforator',
    group: 'posterior',
    family: 'VA',
    from: 'va_v4_dist_{s}@mid',
    to: 'latmed_end_{s}',
    parent: 'va_v4_dist_{s}',
    r: 0.3,
    n: 3,
    path: [
      [4.5, -25.5, -54],
      [7.5, -30, -56],
      [9, -35, -57],
    ],
    pathMode: 'deep',
  }),
  bi({
    id: 'asa_root',
    name: { zh: '前脊髓動脈根部與延髓內側支', en: 'Anterior spinal artery root & medial medullary branches' },
    abbr: 'ASA',
    desc: {
      zh: '左右各一條，向下匯合成前脊髓動脈；沿途供應延髓內側（錐體、內側蹄系、舌下神經核）。',
      en: 'One from each vertebral artery; they join to form the anterior spinal artery and supply the medial medulla (pyramid, medial lemniscus, hypoglossal nucleus).',
    },
    kind: 'perforator',
    group: 'posterior',
    family: 'ASA',
    from: 'va_v4_dist_{s}@mid',
    to: 'asa_top',
    parent: 'va_v4_dist_{s}',
    r: 0.4,
    n: 2,
    path: [
      [4.5, -25.5, -54],
      [2.5, -30, -58],
      [0.5, -33.5, -62],
    ],
    pathMode: 'cistern',
  }),
  mid({
    id: 'asa',
    name: { zh: '前脊髓動脈', en: 'Anterior spinal artery' },
    abbr: 'ASA',
    desc: {
      zh: '沿延髓與脊髓前正中裂往下，供應頸髓前 2/3。',
      en: 'Descends in the anterior median fissure, supplying the anterior two-thirds of the cervical cord.',
    },
    kind: 'branch',
    group: 'posterior',
    family: 'ASA',
    from: 'asa_top',
    to: 'asa_end',
    r: 0.4,
    path: [
      [0, -33.5, -62],
      [0, -35, -68],
      [0, -37, -76],
      [0, -38, -88],
    ],
    pathMode: 'free',
  }),
  bi({
    id: 'pica',
    name: { zh: '小腦後下動脈', en: 'Posterior inferior cerebellar artery' },
    abbr: 'PICA',
    desc: {
      zh: '繞過延髓外側再繞過小腦扁桃體，供應延髓外側與小腦下半部。受損常以眩暈、嘔吐、走不穩表現。',
      en: 'Loops around the lateral medulla and the cerebellar tonsil, supplying the lateral medulla and inferior cerebellum. Occlusion often presents with vertigo, vomiting and unsteadiness.',
    },
    kind: 'branch',
    group: 'posterior',
    family: 'PICA',
    from: 'va_pica_{s}',
    to: 'pica_div_{s}',
    parent: 'va_v4_prox_{s}',
    r: 0.75,
    path: [
      [9, -33, -62],
      [12, -37, -63],
      [13, -43, -65],
      [11, -49, -68],
      [8, -52, -62],
      [6, -54, -55],
      [7, -58, -52],
    ],
    pathMode: 'cistern',
  }),
  bi({
    id: 'pica_medial',
    name: { zh: 'PICA 內側（蚓部）支', en: 'PICA medial (vermian) branch' },
    desc: {
      zh: '供應小腦下蚓部與扁桃體；單獨受損可只表現為眩暈，常被誤診為內耳問題。',
      en: 'Supplies the inferior vermis and tonsil; isolated infarction can mimic benign inner-ear vertigo.',
    },
    kind: 'branch',
    group: 'posterior',
    family: 'PICA',
    from: 'pica_div_{s}',
    to: 'pica_med_end_{s}',
    parent: 'pica_{s}',
    r: 0.55,
    path: [
      [7, -58, -52],
      [4, -64, -50],
      [3, -72, -44],
      [3, -80, -35],
    ],
    pathMode: 'surface',
  }),
  bi({
    id: 'pica_lateral',
    name: { zh: 'PICA 外側（半球）支', en: 'PICA lateral (hemispheric) branch' },
    desc: {
      zh: '供應小腦半球下表面。',
      en: 'Supplies the inferior surface of the cerebellar hemisphere.',
    },
    kind: 'branch',
    group: 'posterior',
    family: 'PICA',
    from: 'pica_div_{s}',
    to: 'pica_lat_end_{s}',
    parent: 'pica_{s}',
    r: 0.6,
    path: [
      [7, -58, -52],
      [16, -66, -56],
      [28, -72, -52],
      [40, -72, -44],
    ],
    pathMode: 'surface',
  }),
  mid({
    id: 'basilar_lower',
    name: { zh: '基底動脈下段', en: 'Basilar artery, lower segment' },
    abbr: 'BA',
    desc: {
      zh: '左右椎動脈在橋腦延髓交界匯合成基底動脈，並分出小腦前下動脈（AICA）。',
      en: 'The two vertebral arteries unite at the pontomedullary junction; this segment gives off the AICAs.',
    },
    kind: 'trunk',
    group: 'posterior',
    family: 'BA',
    from: 'vb_conf',
    to: 'ba_aica',
    r: 1.6,
    path: [
      [0, -19.5, -49],
      [0, -16.5, -46],
      [0, -14.5, -43.5],
    ],
    pathMode: 'cistern',
  }),
  mid({
    id: 'basilar_mid',
    name: { zh: '基底動脈中段', en: 'Basilar artery, middle segment' },
    abbr: 'BA',
    desc: {
      zh: '沿橋腦前方上行，發出供應橋腦下半部的旁正中穿通支。中段阻塞可造成雙側橋腦腹側梗塞——閉鎖症候群。',
      en: 'Ascends in front of the pons giving paramedian perforators to the lower pons. Occlusion can infarct both sides of the ventral pons — locked-in syndrome.',
    },
    kind: 'trunk',
    group: 'posterior',
    family: 'BA',
    from: 'ba_aica',
    to: 'ba_rostral',
    r: 1.55,
    path: [
      [0, -14.5, -43.5],
      [0, -12, -38],
      [0, -10.5, -33],
    ],
    pathMode: 'cistern',
  }),
  mid({
    id: 'basilar_upper',
    name: { zh: '基底動脈上段', en: 'Basilar artery, upper segment' },
    abbr: 'BA',
    desc: {
      zh: '發出供應橋腦上半部的穿通支，並在上端分出小腦上動脈。',
      en: 'Gives perforators to the upper pons and the superior cerebellar arteries at its top.',
    },
    kind: 'trunk',
    group: 'posterior',
    family: 'BA',
    from: 'ba_rostral',
    to: 'ba_sca',
    r: 1.5,
    path: [
      [0, -10.5, -33],
      [0, -10.2, -29],
      [0, -10.6, -25.5],
    ],
    pathMode: 'cistern',
  }),
  mid({
    id: 'basilar_tip',
    name: { zh: '基底動脈頂端', en: 'Basilar tip' },
    abbr: 'BA tip',
    desc: {
      zh: '分叉成左右後大腦動脈，並發出供應中腦與視丘的穿通支。栓子常卡在此（頂端症候群）：意識改變、眼球運動障礙、雙側視野缺損。',
      en: 'Bifurcates into the two PCAs and gives perforators to the midbrain and thalami. Emboli often lodge here ("top of the basilar"): altered consciousness, eye-movement disorders, bilateral visual loss.',
    },
    kind: 'trunk',
    group: 'posterior',
    family: 'BA',
    from: 'ba_sca',
    to: 'ba_tip',
    r: 1.4,
    path: [
      [0, -10.6, -25.5],
      [0, -11.2, -23],
      [0, -12, -20.5],
    ],
    pathMode: 'cistern',
    occludesDistalJunction: true,
  }),
  bi({
    id: 'aica',
    name: { zh: '小腦前下動脈', en: 'Anterior inferior cerebellar artery' },
    abbr: 'AICA',
    desc: {
      zh: '供應橋腦下部外側、小腦中腳、絨球與小腦前下表面，並分出迷路動脈到內耳。受損時常合併同側聽力喪失。',
      en: 'Supplies the lateral lower pons, middle cerebellar peduncle, flocculus and anterior-inferior cerebellum, and gives the labyrinthine artery to the inner ear — so deafness is common with AICA stroke.',
    },
    kind: 'branch',
    group: 'posterior',
    family: 'AICA',
    from: 'ba_aica',
    to: 'aica_end_{s}',
    parent: 'basilar_lower',
    r: 0.6,
    path: [
      [0, -14.5, -43.5],
      [6, -17, -44],
      [13, -22, -44],
      [19, -26, -42],
      [22, -33, -41],
      [24, -41, -40],
      [32, -48, -42],
    ],
    pathMode: 'cistern',
  }),
  bi({
    id: 'labyrinthine',
    name: { zh: '迷路動脈（內聽動脈）', en: 'Labyrinthine (internal auditory) artery' },
    desc: {
      zh: '供應耳蝸與前庭的終末動脈。阻塞會造成突發單側耳聾與眩暈。',
      en: 'End-artery to the cochlea and vestibule; occlusion causes sudden unilateral deafness and vertigo.',
    },
    kind: 'perforator',
    group: 'posterior',
    family: 'AICA',
    from: 'aica_{s}@mid',
    to: 'lab_end_{s}',
    parent: 'aica_{s}',
    r: 0.25,
    n: 2,
    path: [
      [16, -24, -43.5],
      [22, -22, -41],
      [28, -20, -39],
      [33, -18, -38],
    ],
    pathMode: 'free',
  }),
  bi({
    id: 'pontine_paramedian_inferior',
    name: { zh: '橋腦最下部旁正中穿通支', en: 'Inferior pontine paramedian perforators' },
    desc: {
      zh: '由基底動脈下段（兩條椎動脈匯合後、小腦前下動脈之前）穿入橋腦下緣。基底動脈近端阻塞時，即使後交通動脈把血逆送回來，這些分支仍會一起被堵住。',
      en: 'Enter the lowest pons from the lower basilar (between the vertebral confluence and the AICAs). In a proximal basilar occlusion they are cut off even when the posterior communicating arteries refill the basilar from above.',
    },
    kind: 'perforator',
    group: 'posterior',
    family: 'BA',
    from: 'basilar_lower@mid',
    to: 'ppi_end_{s}',
    parent: 'basilar_lower',
    r: 0.22,
    n: 3,
    path: [
      [0, -19.7, -47.5],
      [2.5, -22, -47],
      [3.5, -28, -45.5],
      [4, -33, -44],
    ],
    pathMode: 'deep',
  }),
  bi({
    id: 'pontine_paramedian_caudal',
    name: { zh: '橋腦下部旁正中穿通支', en: 'Caudal pontine paramedian perforators' },
    desc: {
      zh: '由基底動脈中段直接穿入橋腦，供應皮質脊髓徑、外展神經核與內側縱束。高血壓小血管病的好發處。',
      en: 'Penetrate directly from the mid-basilar into the pons, supplying the corticospinal tract, abducens nucleus region and MLF. Common site of hypertensive small-vessel disease.',
    },
    kind: 'perforator',
    group: 'posterior',
    family: 'BA',
    from: 'basilar_mid@mid',
    to: 'ppc_end_{s}',
    parent: 'basilar_mid',
    r: 0.25,
    n: 4,
    path: [
      [0, -12, -38.2],
      [2.5, -15, -38],
      [3.5, -22, -37],
      [4, -30, -36],
    ],
    pathMode: 'deep',
  }),
  bi({
    id: 'pontine_paramedian_rostral',
    name: { zh: '橋腦上部旁正中穿通支', en: 'Rostral pontine paramedian perforators' },
    desc: {
      zh: '供應橋腦上部腹側（運動路徑）與被蓋旁正中。',
      en: 'Supply the upper ventral pons (motor pathways) and paramedian tegmentum.',
    },
    kind: 'perforator',
    group: 'posterior',
    family: 'BA',
    from: 'basilar_upper@mid',
    to: 'ppr_end_{s}',
    parent: 'basilar_upper',
    r: 0.25,
    n: 4,
    path: [
      [0, -10.2, -29.2],
      [2.5, -14, -29],
      [3.5, -21, -28.5],
      [4, -30, -28],
    ],
    pathMode: 'deep',
  }),
  bi({
    id: 'pontine_circumferential',
    name: { zh: '橋腦短環繞支', en: 'Short circumferential pontine arteries' },
    desc: {
      zh: '繞到橋腦外側，供應三叉神經、顏面神經核附近的外側橋腦。',
      en: 'Wrap around to the lateral pons near the trigeminal and facial nuclei.',
    },
    kind: 'perforator',
    group: 'posterior',
    family: 'BA',
    from: 'basilar_mid@mid',
    to: 'pcirc_end_{s}',
    parent: 'basilar_mid',
    r: 0.3,
    n: 3,
    path: [
      [0, -12, -38.2],
      [7, -13.5, -37.5],
      [13, -18, -36],
      [16, -26, -34],
    ],
    pathMode: 'cistern',
  }),
  bi({
    id: 'sca',
    name: { zh: '小腦上動脈', en: 'Superior cerebellar artery' },
    abbr: 'SCA',
    desc: {
      zh: '繞過中腦橋腦交界，供應小腦上半部、齒狀核與橋腦上部外側。',
      en: 'Encircles the pontomesencephalic junction to supply the superior cerebellum, dentate nucleus and upper lateral pons.',
    },
    kind: 'branch',
    group: 'posterior',
    family: 'SCA',
    from: 'ba_sca',
    to: 'sca_div_{s}',
    parent: 'basilar_upper',
    r: 0.8,
    path: [
      [0, -10.6, -25.5],
      [6, -12, -25],
      [12, -17, -24],
      [16.5, -25, -22],
      [17.5, -34, -20],
      [15, -42, -17],
    ],
    pathMode: 'cistern',
  }),
  bi({
    id: 'sca_medial',
    name: { zh: 'SCA 內側（上蚓部）支', en: 'SCA medial (superior vermian) branch' },
    desc: {
      zh: '供應小腦上蚓部與齒狀核。',
      en: 'Supplies the superior vermis and dentate nucleus.',
    },
    kind: 'branch',
    group: 'posterior',
    family: 'SCA',
    from: 'sca_div_{s}',
    to: 'sca_med_end_{s}',
    parent: 'sca_{s}',
    r: 0.55,
    path: [
      [15, -42, -17],
      [9, -48, -12],
      [4, -56, -9],
      [3, -66, -14],
    ],
    pathMode: 'surface',
  }),
  bi({
    id: 'sca_lateral',
    name: { zh: 'SCA 外側（半球）支', en: 'SCA lateral (hemispheric) branch' },
    desc: {
      zh: '供應小腦半球上表面，受損造成同側肢體運動失調與構音障礙。',
      en: 'Supplies the superior surface of the hemisphere; damage gives same-side limb ataxia and dysarthria.',
    },
    kind: 'branch',
    group: 'posterior',
    family: 'SCA',
    from: 'sca_div_{s}',
    to: 'sca_lat_end_{s}',
    parent: 'sca_{s}',
    r: 0.6,
    path: [
      [15, -42, -17],
      [24, -50, -18],
      [34, -60, -22],
      [42, -70, -28],
    ],
    pathMode: 'surface',
  }),
  bi({
    id: 'mesencephalic_perf',
    name: { zh: '中腦旁正中穿通支', en: 'Mesencephalic paramedian perforators' },
    desc: {
      zh: '由基底動脈頂端發出，供應中腦旁正中：動眼神經核、紅核、垂直眼動中樞與網狀活化系統。',
      en: 'From the basilar tip to the paramedian midbrain: oculomotor nucleus, red nucleus, vertical gaze centres and the reticular activating system.',
    },
    kind: 'perforator',
    group: 'posterior',
    family: 'THAL',
    from: 'basilar_tip@mid',
    to: 'mesperf_end_{s}',
    parent: 'basilar_tip',
    r: 0.25,
    n: 3,
    path: [
      [0, -11.2, -23],
      [2.5, -14, -19],
      [3.5, -18, -14],
      [4, -22, -9],
    ],
    pathMode: 'deep',
  }),
  bi({
    id: 'pca_p1',
    name: { zh: '後大腦動脈 P1 段', en: 'Posterior cerebral artery, P1 segment' },
    abbr: 'P1',
    desc: {
      zh: '基底動脈頂端到後交通動脈匯入點。「胚胎型後大腦動脈」的人 P1 很細，後大腦動脈改由內頸動脈供血。',
      en: 'From the basilar tip to the PComm junction. In a "fetal PCA" the P1 is tiny and the PCA is fed from the ICA instead.',
    },
    kind: 'trunk',
    group: 'willis',
    family: 'PCA',
    from: 'ba_tip',
    to: 'pca_pcomm_{s}',
    parent: 'basilar_tip',
    r: 1.0,
    path: [
      [0, -12, -20.5],
      [5, -12.5, -19.5],
      [10, -14, -18.5],
    ],
    pathMode: 'cistern',
  }),
  bi({
    id: 'thalamoperforator',
    name: { zh: '視丘穿通動脈（旁正中）', en: 'Thalamoperforating (paramedian) arteries' },
    desc: {
      zh: '由 P1 發出，供應視丘旁正中（內背核、板內核），部分人也供應中腦上部。部分人只有一條共同主幹（Percheron 動脈）同時供應兩側。',
      en: 'From P1 to the paramedian thalamus (mediodorsal, intralaminar nuclei) and, in some people, the upper midbrain. Some people have a single trunk (artery of Percheron) feeding both sides.',
    },
    kind: 'perforator',
    group: 'posterior',
    family: 'THAL',
    from: 'pca_p1_{s}@mid',
    to: 'thalperf_end_{s}',
    parent: 'pca_p1_{s}',
    r: 0.3,
    n: 2,
    path: [
      [5, -12.5, -19.5],
      [4.5, -15, -12],
      [4.5, -16, -3],
      [5, -16, 5],
    ],
    pathMode: 'deep',
  }),
  bi({
    id: 'quadrigeminal',
    name: { zh: '四疊體動脈（丘動脈）', en: 'Quadrigeminal (collicular) artery' },
    desc: {
      zh: '繞過中腦到上、下丘，供應中腦背側與外側。',
      en: 'Encircles the midbrain to the superior and inferior colliculi, supplying the dorsal and lateral midbrain.',
    },
    kind: 'perforator',
    group: 'posterior',
    family: 'PCA',
    from: 'pca_p1_{s}@mid',
    to: 'quad_end_{s}',
    parent: 'pca_p1_{s}',
    r: 0.3,
    path: [
      [5, -12.5, -19.5],
      [11, -19, -19],
      [15, -28, -16],
      [12, -35, -11],
      [6, -38, -7],
    ],
    pathMode: 'cistern',
  }),
  bi({
    id: 'pca_p2',
    name: { zh: '後大腦動脈 P2 段', en: 'Posterior cerebral artery, P2 segment' },
    abbr: 'P2',
    desc: {
      zh: '繞過大腦腳往後走，發出供應視丘外側與後部的分支，再分成供應枕葉與顳葉內下側的皮質支。未治療的阻塞通常造成對側同側偏盲。',
      en: 'Wraps around the cerebral peduncle, gives branches to the lateral and posterior thalamus, then divides into cortical branches to the occipital and inferomedial temporal lobes. Untreated occlusion usually leaves a contralateral homonymous hemianopia.',
    },
    kind: 'trunk',
    group: 'posterior',
    family: 'PCA',
    from: 'pca_pcomm_{s}',
    to: 'pca_p2_end_{s}',
    // calibration (C1-F3): the clot is taken to reach the terminal division, so the collaterals
    // that fill one cortical branch backwards cannot run on through the division into the
    // others. Otherwise the leptomeningeal inflow of all branches pooled there and a P2
    // occlusion left less ischaemia in the calcarine cortex than an occlusion of the calcarine
    // artery alone. A visual field defect is the main sign of superficial PCA infarcts
    // (hemianopia 67 %, quadrantanopia 22 %, bilateral 7 % of 117: Cals N et al. J Neurol
    // 2002;249:855-861, PMID 12140669; Kumral E et al. Eur J Neurol 2004;11:237-246, PMID 15061825).
    occludesDistalJunction: true,
    parent: 'pca_p1_{s}',
    r: 1.0,
    path: [
      [10, -14, -18.5],
      [16, -19, -16.5],
      [20, -26, -14],
      [22, -34, -10],
      [20, -43, -5],
      [15, -51, -1],
    ],
    pathMode: 'cistern',
  }),
  bi({
    id: 'thalamogeniculate',
    name: { zh: '視丘膝狀體動脈', en: 'Thalamogeniculate arteries' },
    desc: {
      zh: '供應視丘腹後外側核（感覺轉運站）。阻塞造成對側純感覺中風，數週後可能出現中樞性疼痛。',
      en: 'Supply the ventral posterolateral thalamus (the sensory relay). Occlusion gives a pure sensory stroke and sometimes delayed central pain.',
    },
    kind: 'perforator',
    group: 'posterior',
    family: 'THAL',
    from: 'pca_p2_{s}@mid',
    to: 'thalgen_end_{s}',
    parent: 'pca_p2_{s}',
    r: 0.3,
    n: 2,
    path: [
      [21, -30, -12],
      [20, -26, -5],
      [18, -22, 1],
    ],
    pathMode: 'deep',
  }),
  bi({
    id: 'posterior_choroidal',
    name: { zh: '後脈絡叢動脈', en: 'Posterior choroidal arteries' },
    desc: {
      zh: '供應視丘枕、外側膝狀體與脈絡叢；在脈絡叢處與前脈絡叢動脈相吻合，但供應視丘的分支在吻合處之前就已分出。',
      en: 'Supply the pulvinar, lateral geniculate body and choroid plexus; they meet the anterior choroidal artery at the choroid plexus, but their thalamic branches leave before that anastomosis.',
    },
    kind: 'perforator',
    group: 'posterior',
    family: 'PCA',
    from: 'pca_p2_{s}@mid',
    to: 'pchor_end_{s}',
    parent: 'pca_p2_{s}',
    r: 0.3,
    path: [
      [21, -30, -12],
      [19, -36, -4],
      [15, -33, 5],
      [12, -28, 11],
    ],
    pathMode: 'deep',
  }),
  bi({
    id: 'pca_temporal',
    name: { zh: '後大腦動脈顳支', en: 'PCA temporal branches' },
    desc: {
      zh: '供應海馬迴、海馬旁迴、梭狀迴與顳葉下表面（記憶、臉孔辨識、顏色）。',
      en: 'Supply the hippocampus, parahippocampal and fusiform gyri and inferior temporal surface (memory, face recognition, colour).',
    },
    kind: 'branch',
    group: 'posterior',
    family: 'PCA',
    from: 'pca_p2_{s}@mid',
    to: 'pca_temp_end_{s}',
    parent: 'pca_p2_{s}',
    r: 0.7,
    path: [
      [21, -30, -12],
      [28, -26, -24],
      [34, -38, -26],
      [37, -52, -20],
      [36, -66, -12],
    ],
    pathMode: 'surface',
    surfaceFrom: 0.15,
  }),
  bi({
    id: 'pca_calcarine',
    name: { zh: '距狀動脈', en: 'Calcarine artery' },
    desc: {
      zh: '沿距狀溝走，供應初級視覺皮質（距狀溝上下唇；上唇的楔葉也由頂枕動脈供應）。阻塞造成對側同側偏盲。',
      en: 'Runs in the calcarine fissure to the primary visual cortex (both banks; the upper bank, the cuneus, shares the parieto-occipital artery); occlusion gives a contralateral homonymous hemianopia.',
    },
    kind: 'branch',
    group: 'posterior',
    family: 'PCA',
    from: 'pca_p2_end_{s}',
    to: 'pca_calc_end_{s}',
    parent: 'pca_p2_{s}',
    r: 0.8,
    path: [
      [15, -51, -1],
      [10, -62, 2],
      [7, -74, 4],
      [8, -88, 4],
      [12, -100, 4],
    ],
    pathMode: 'surface',
  }),
  bi({
    id: 'pca_parietooccipital',
    name: { zh: '頂枕動脈', en: 'Parieto-occipital artery' },
    desc: {
      zh: '沿頂枕溝往上，供應楔前葉後部，並與距狀動脈共同供應楔葉。',
      en: 'Ascends in the parieto-occipital sulcus to the posterior precuneus, and shares the cuneus with the calcarine artery.',
    },
    kind: 'branch',
    group: 'posterior',
    family: 'PCA',
    from: 'pca_p2_end_{s}',
    to: 'pca_po_end_{s}',
    parent: 'pca_p2_{s}',
    r: 0.7,
    path: [
      [15, -51, -1],
      [9, -58, 10],
      [7, -64, 22],
      [6, -70, 36],
      [8, -74, 48],
    ],
    pathMode: 'surface',
  }),
  bi({
    id: 'pca_splenial',
    name: { zh: '胼胝體壓部動脈（後胼胝體周動脈）', en: 'Splenial (posterior pericallosal) artery' },
    desc: {
      zh: '供應胼胝體壓部。左側後大腦動脈合併壓部受損會出現「失讀不失寫」。',
      en: 'Supplies the splenium. Left PCA infarction including the splenium causes "alexia without agraphia".',
    },
    kind: 'branch',
    group: 'posterior',
    family: 'PCA',
    from: 'pca_parietooccipital_{s}@mid',
    to: 'pca_spl_end_{s}',
    parent: 'pca_parietooccipital_{s}',
    r: 0.4,
    path: [
      [7, -64, 22],
      [5, -54, 15],
      [4, -46, 17],
      [3, -40, 24],
    ],
    pathMode: 'surface',
  }),

  // ════════════════════════ Collateral pathways ════════════════════════
  // Leptomeningeal (pial) anastomoses: tiny vessels over the cortex whose strength differs
  // hugely between people; they decide how much penumbra survives a large-vessel occlusion.
  bi({
    id: 'lepto_aca_mca_precentral',
    name: { zh: '軟腦膜側枝：前↔中大腦動脈（運動區）', en: 'Leptomeningeal collateral: ACA ↔ MCA (motor strip)' },
    desc: {
      zh: '腦表面前、中大腦動脈末梢間的細小吻合。大血管阻塞時可逆向灌注，側枝好壞決定梗塞大小。',
      en: 'Fine pial anastomoses between ACA and MCA endings. After a large-vessel occlusion they fill the territory backwards; their quality largely decides final infarct size.',
    },
    kind: 'collateral',
    group: 'collateral',
    family: 'COLL',
    from: 'aca_cm_end_{s}',
    to: 'mca_prc_end_{s}',
    r: 0.25,
    path: [
      [5, -10, 64],
      [22, -12, 66],
      [42, -13, 58],
    ],
    pathMode: 'surface',
    collStrength: 0.6,
  }),
  bi({
    id: 'lepto_aca_mca_central',
    name: { zh: '軟腦膜側枝：前↔中大腦動脈（感覺區）', en: 'Leptomeningeal collateral: ACA ↔ MCA (sensory strip)' },
    desc: {
      zh: '旁中央動脈與中央動脈之間的吻合。',
      en: 'Anastomoses between the paracentral and central arteries.',
    },
    kind: 'collateral',
    group: 'collateral',
    family: 'COLL',
    from: 'aca_para_end_{s}',
    to: 'mca_cen_end_{s}',
    r: 0.25,
    path: [
      [7, -32, 74],
      [26, -30, 70],
      [44, -28, 60],
    ],
    pathMode: 'surface',
    collStrength: 0.7,
  }),
  bi({
    id: 'lepto_aca_mca_parietal',
    name: { zh: '軟腦膜側枝：前↔中大腦動脈（頂葉）', en: 'Leptomeningeal collateral: ACA ↔ MCA (parietal)' },
    desc: { zh: '旁中央動脈與頂前動脈之間的吻合。', en: 'Paracentral ↔ anterior parietal anastomoses.' },
    kind: 'collateral',
    group: 'collateral',
    family: 'COLL',
    from: 'aca_para_end_{s}',
    to: 'mca_ap_end_{s}',
    r: 0.25,
    path: [
      [7, -32, 74],
      [26, -42, 68],
      [44, -47, 57],
    ],
    pathMode: 'surface',
    collStrength: 0.8,
  }),
  bi({
    id: 'lepto_aca_mca_frontal',
    name: { zh: '軟腦膜側枝：前↔中大腦動脈（額葉）', en: 'Leptomeningeal collateral: ACA ↔ MCA (frontal)' },
    desc: { zh: '額極動脈與前額動脈之間的吻合。', en: 'Frontopolar ↔ prefrontal anastomoses.' },
    kind: 'collateral',
    group: 'collateral',
    family: 'COLL',
    from: 'aca_fp_end_{s}',
    to: 'mca_pf_end_{s}',
    r: 0.25,
    path: [
      [7, 65, 6],
      [24, 60, 22],
      [40, 50, 32],
    ],
    pathMode: 'surface',
    collStrength: 0.8,
  }),
  bi({
    id: 'lepto_aca_mca_orbital',
    name: { zh: '軟腦膜側枝：前↔中大腦動脈（眼眶面）', en: 'Leptomeningeal collateral: ACA ↔ MCA (orbital)' },
    desc: { zh: '眼眶額葉內外側之間的吻合。', en: 'Medial ↔ lateral orbitofrontal anastomoses.' },
    kind: 'collateral',
    group: 'collateral',
    family: 'COLL',
    from: 'aca_fp_end_{s}',
    to: 'mca_of_end_{s}',
    r: 0.25,
    path: [
      [7, 65, 6],
      [22, 60, -4],
      [36, 52, -6],
    ],
    pathMode: 'surface',
    collStrength: 0.5,
  }),
  bi({
    id: 'lepto_pca_mca_parietal',
    name: { zh: '軟腦膜側枝：後↔中大腦動脈（頂枕）', en: 'Leptomeningeal collateral: PCA ↔ MCA (parieto-occipital)' },
    desc: { zh: '頂枕動脈與角迴動脈之間的吻合。', en: 'Parieto-occipital ↔ angular anastomoses.' },
    kind: 'collateral',
    group: 'collateral',
    family: 'COLL',
    from: 'pca_po_end_{s}',
    to: 'mca_ang_end_{s}',
    r: 0.25,
    path: [
      [8, -74, 48],
      [28, -72, 46],
      [45, -66, 37],
    ],
    pathMode: 'surface',
    collStrength: 0.8,
  }),
  bi({
    id: 'lepto_pca_mca_superior_parietal',
    name: { zh: '軟腦膜側枝：後↔中大腦動脈（頂上）', en: 'Leptomeningeal collateral: PCA ↔ MCA (superior parietal)' },
    desc: { zh: '頂枕動脈與頂後動脈之間的吻合。', en: 'Parieto-occipital ↔ posterior parietal anastomoses.' },
    kind: 'collateral',
    group: 'collateral',
    family: 'COLL',
    from: 'pca_po_end_{s}',
    to: 'mca_pp_end_{s}',
    r: 0.25,
    path: [
      [8, -74, 48],
      [26, -64, 56],
      [43, -55, 54],
    ],
    pathMode: 'surface',
    collStrength: 0.55,
  }),
  bi({
    id: 'lepto_pca_mca_occipital',
    name: { zh: '軟腦膜側枝：後↔中大腦動脈（枕葉）', en: 'Leptomeningeal collateral: PCA ↔ MCA (occipital)' },
    desc: {
      zh: '距狀動脈與顳枕動脈之間的吻合——枕極中心視力得以保留的原因之一。',
      en: 'Calcarine ↔ temporo-occipital anastomoses — one reason central (macular) vision can be spared.',
    },
    kind: 'collateral',
    group: 'collateral',
    family: 'COLL',
    from: 'pca_calc_end_{s}',
    to: 'mca_to_end_{s}',
    r: 0.25,
    path: [
      [12, -100, 4],
      [26, -96, 4],
      [38, -88, 2],
    ],
    pathMode: 'surface',
    collStrength: 0.7,
  }),
  bi({
    id: 'lepto_pca_mca_temporal',
    name: { zh: '軟腦膜側枝：後↔中大腦動脈（顳葉）', en: 'Leptomeningeal collateral: PCA ↔ MCA (temporal)' },
    desc: { zh: '後大腦動脈顳支與顳中動脈之間的吻合。', en: 'PCA temporal ↔ middle temporal anastomoses.' },
    kind: 'collateral',
    group: 'collateral',
    family: 'COLL',
    from: 'pca_temp_end_{s}',
    to: 'mca_tm_end_{s}',
    r: 0.25,
    path: [
      [36, -66, -12],
      [54, -52, -16],
      [63, -36, -12],
    ],
    pathMode: 'surface',
    collStrength: 0.6,
  }),
  bi({
    id: 'lepto_aca_pca_callosal',
    name: { zh: '胼胝體周側枝：前↔後大腦動脈', en: 'Pericallosal collateral: ACA ↔ PCA' },
    desc: {
      zh: '胼胝體周動脈與壓部動脈在胼胝體後方相接。',
      en: 'Pericallosal and splenial arteries meet behind the corpus callosum.',
    },
    kind: 'collateral',
    group: 'collateral',
    family: 'COLL',
    from: 'aca_pc_end_{s}',
    to: 'pca_spl_end_{s}',
    r: 0.3,
    path: [
      [3, -38, 27],
      [3, -39, 25],
      [3, -40, 24],
    ],
    pathMode: 'surface',
    collStrength: 0.6,
  }),
  bi({
    id: 'lepto_pica_aica',
    name: { zh: '小腦側枝：PICA ↔ AICA', en: 'Cerebellar collateral: PICA ↔ AICA' },
    desc: { zh: '小腦表面的動脈吻合。', en: 'Surface anastomoses over the cerebellum.' },
    kind: 'collateral',
    group: 'collateral',
    family: 'COLL',
    from: 'pica_lat_end_{s}',
    to: 'aica_end_{s}',
    r: 0.25,
    path: [
      [40, -72, -44],
      [38, -60, -46],
      [32, -48, -42],
    ],
    pathMode: 'surface',
    // R4-3: a little stronger than the other cerebellar links (0.08). Once the left–right PICA
    // link was weakened (lepto_pica_crossed, C7-F2), a whole-PICA occlusion lost the supply it got
    // across the midline: with good collaterals its territory fell below the core threshold, so
    // collaterals and reopening even at 30 min no longer changed the infarct. The PICA trunk
    // territory is now held through the hemispheric anastomoses with the AICA and the SCA instead
    // (this one and lepto_pica_sca_lateral): with good collaterals it sits just above the core
    // threshold, as before C7-F2, while the medial and the lateral branch alone still infarct
    // their territories. TODO(medical-review): strength
    collStrength: 0.105,
  }),
  bi({
    id: 'lepto_aica_sca',
    name: { zh: '小腦側枝：AICA ↔ SCA', en: 'Cerebellar collateral: AICA ↔ SCA' },
    desc: { zh: '小腦表面的動脈吻合。', en: 'Surface anastomoses over the cerebellum.' },
    kind: 'collateral',
    group: 'collateral',
    family: 'COLL',
    from: 'aica_end_{s}',
    to: 'sca_lat_end_{s}',
    r: 0.25,
    path: [
      [32, -48, -42],
      [40, -60, -34],
      [42, -70, -28],
    ],
    pathMode: 'surface',
    collStrength: 0.08,
  }),
  bi({
    id: 'lepto_pica_sca_lateral',
    name: { zh: '小腦側枝：PICA ↔ SCA（半球）', en: 'Cerebellar collateral: PICA ↔ SCA (hemisphere)' },
    desc: { zh: '小腦半球後緣的動脈吻合。', en: 'Anastomoses along the posterior hemisphere.' },
    kind: 'collateral',
    group: 'collateral',
    family: 'COLL',
    from: 'pica_lat_end_{s}',
    to: 'sca_lat_end_{s}',
    r: 0.25,
    path: [
      [40, -72, -44],
      [44, -74, -36],
      [42, -70, -28],
    ],
    pathMode: 'surface',
    // R4-3: see lepto_pica_aica. TODO(medical-review): strength
    collStrength: 0.105,
  }),
  bi({
    id: 'lepto_pica_sca_vermian',
    name: { zh: '小腦側枝：PICA ↔ SCA（蚓部）', en: 'Cerebellar collateral: PICA ↔ SCA (vermis)' },
    desc: { zh: '蚓部上下之間的吻合。', en: 'Anastomoses between the superior and inferior vermis.' },
    kind: 'collateral',
    group: 'collateral',
    family: 'COLL',
    from: 'pica_med_end_{s}',
    to: 'sca_med_end_{s}',
    r: 0.25,
    path: [
      [3, -80, -35],
      [3, -76, -24],
      [3, -66, -14],
    ],
    pathMode: 'surface',
    collStrength: 0.08,
  }),
  mid({
    id: 'lepto_pica_crossed',
    name: { zh: '小腦側枝：左右 PICA 跨中線', en: 'Cerebellar collateral: PICA across midline' },
    desc: { zh: '下蚓部左右 PICA 之間的吻合。', en: 'Left–right PICA anastomoses over the inferior vermis.' },
    kind: 'collateral',
    group: 'collateral',
    family: 'COLL',
    from: 'pica_med_end_r',
    to: 'pica_med_end_l',
    r: 0.25,
    path: [
      [3, -80, -35],
      [0, -81, -35],
      [-3, -80, -35],
    ],
    pathMode: 'surface',
    // weak: with 0.08 this and the vermian anastomosis to the SCA refilled a medial PICA branch
    // completely, so its occlusion caused nothing under the default collaterals — yet the medial
    // branch territory is the commonest PICA infarct (23 of 74: Kumral E et al. Cerebrovasc Dis
    // 2005;20:370–380, PMID 16205055) and gives nearly all cerebellar infarcts that mimic
    // vestibular neuritis (24 of 25: Lee H et al. Neurology 2006;67:1178–1183, PMID 17030749).
    // Only this PICA-to-PICA link is weakened: the shared PICA–SCA anastomosis is left as it was,
    // so an SCA occlusion behaves as before (that series had no such SCA presentation). C7-F2.
    // TODO(medical-review): strength
    collStrength: 0.01,
  }),
  mid({
    id: 'lepto_sca_crossed',
    name: { zh: '小腦側枝：左右 SCA 跨中線', en: 'Cerebellar collateral: SCA across midline' },
    desc: { zh: '上蚓部左右 SCA 之間的吻合。', en: 'Left–right SCA anastomoses over the superior vermis.' },
    kind: 'collateral',
    group: 'collateral',
    family: 'COLL',
    from: 'sca_med_end_r',
    to: 'sca_med_end_l',
    r: 0.25,
    path: [
      [3, -66, -14],
      [0, -67, -13],
      [-3, -66, -14],
    ],
    pathMode: 'surface',
    collStrength: 0.08,
  }),
  bi({
    id: 'coll_acha_pchor',
    name: { zh: '脈絡叢側枝：前↔後脈絡叢動脈', en: 'Choroidal collateral: AChA ↔ posterior choroidal' },
    desc: {
      zh: '在側腦室脈絡叢處前後脈絡叢動脈相通。',
      en: 'Anterior and posterior choroidal arteries communicate at the choroid plexus.',
    },
    kind: 'collateral',
    group: 'collateral',
    family: 'COLL',
    from: 'acha_end_{s}',
    to: 'pchor_end_{s}',
    r: 0.2,
    path: [
      [28, -23, -11],
      [22, -30, 0],
      [12, -28, 11],
    ],
    pathMode: 'deep',
    collStrength: 0.5,
  }),
  bi({
    id: 'coll_ec_ic_orbital',
    name: { zh: '顱內外側枝：顏面動脈↔眼動脈', en: 'EC–IC collateral: facial ↔ ophthalmic' },
    desc: {
      zh: '外頸動脈的角動脈與眼動脈末梢在內眼角吻合。內頸動脈阻塞時，血液可經此逆流進入顱內。',
      en: 'The angular branch of the facial artery meets the ophthalmic artery at the inner canthus; after ICA occlusion blood can flow backwards into the skull this way.',
    },
    kind: 'collateral',
    group: 'collateral',
    family: 'COLL',
    from: 'facial_end_{s}',
    to: 'ophth_end_{s}',
    r: 0.3,
    path: [
      [18, 60, -40],
      [24, 56, -38],
      [30, 49, -36],
    ],
    pathMode: 'free',
    collStrength: 1.2,
  }),
  bi({
    id: 'coll_ec_ic_meningeal',
    name: { zh: '顱內外側枝：中腦膜動脈↔眼動脈', en: 'EC–IC collateral: middle meningeal ↔ ophthalmic' },
    desc: { zh: '經眶上裂的腦膜返支吻合。', en: 'Recurrent meningeal anastomosis through the superior orbital fissure.' },
    kind: 'collateral',
    group: 'collateral',
    family: 'COLL',
    from: 'eca_maxillary_{s}@mid',
    to: 'ophth_end_{s}',
    r: 0.25,
    path: [
      [34, 12, -62],
      [32, 30, -46],
      [30, 49, -36],
    ],
    pathMode: 'free',
    collStrength: 0.8,
  }),
  bi({
    id: 'coll_occipital_va',
    name: { zh: '頸部側枝：枕動脈↔椎動脈', en: 'Neck collateral: occipital ↔ vertebral' },
    desc: {
      zh: '外頸動脈枕支與椎動脈肌支在頸部吻合。',
      en: 'Occipital branch of the ECA anastomoses with muscular branches of the vertebral artery.',
    },
    kind: 'collateral',
    group: 'collateral',
    family: 'COLL',
    from: 'eca_occipital_{s}@mid',
    to: 'va_extracranial_{s}@mid',
    r: 0.3,
    path: [
      [40, -40, -91],
      [34, -30, -96],
      [28, -20, -100],
    ],
    pathMode: 'free',
    collStrength: 0.8,
  }),
];
