// @vitest-environment jsdom
import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { Vector3 } from 'three';
import type { SimResult } from '../engine/simulate';
import { useApp } from '../state/store';
import { MRA_DISTAL } from '../i18n/mraDistal';
import source from '../../public/data/mra-distal.json';
const mocks = vi.hoisted(() => ({ load: vi.fn() }));
vi.mock('./mraDistalData', () => ({ loadMraDistal: mocks.load }));
vi.mock('../state/webgl', () => ({ hasWebGL: () => true, defaultView: () => '3d' }));
vi.mock('@react-three/fiber', () => ({ Canvas: ({ children }: { children: React.ReactNode }) => <div>{children}</div>, useFrame: vi.fn(), useThree: () => ({ camera: { position: new Vector3(1, 2, 3) }, controls: { target: new Vector3(), update: vi.fn() }, invalidate: vi.fn() }) }));
vi.mock('@react-three/drei', () => ({ OrbitControls: () => null }));
vi.mock('./brainData', () => ({ useBrainData: () => ({ data: null, error: null }) }));
vi.mock('./BrainMeshes', () => ({ BrainMeshes: () => null }));
vi.mock('./Vessels', () => ({ Vessels: () => <span data-testid="simulation-vessels" /> }));
vi.mock('./MraDistalVessels', () => ({ MraDistalVessels: () => <span data-testid="source-vessels" /> }));
vi.mock('./FlowParticles', () => ({ FlowParticles: () => <span data-testid="flow" /> }));
vi.mock('./Markers', () => ({ ExtraStructures: () => null, ClotMarkers: () => <span data-testid="clots" /> }));
vi.mock('./EmbolusAnimation', () => ({ EmbolusAnimation: () => <span data-testid="embolus" /> }));
vi.mock('./SceneKeyboard', () => ({ KeyboardCamera: () => null, KeyboardFocus: ({ position }: { position: Vector3 | null }) => <span data-testid="focus" data-position={position?.toArray().join(',') ?? ''} />, SceneKeyboard: ({ includeVessels }: { includeVessels: boolean }) => <span data-testid="keyboard" data-vessels={String(includeVessels)} /> }));
import { Scene3D } from './Scene3D';

const sim = {} as SimResult;
const initial = useApp.getState();
beforeEach(() => { mocks.load.mockReset(); useApp.setState({ ...initial, lang: 'en' }); });
afterEach(cleanup);
it('replaces the vessel display only after loading, keeps simulation state and running embolus lifecycle', async () => {
  let resolve: (value: unknown) => void = () => {};
  mocks.load.mockReturnValue(new Promise(value => { resolve = value; }));
  const before = structuredClone({ occlusions: useApp.getState().occlusions, variants: useApp.getState().variants, map: useApp.getState().map });
  render(<Scene3D sim={sim} />);
  expect(screen.getByTestId('simulation-vessels')).toBeTruthy();
  fireEvent.click(screen.getByText(MRA_DISTAL.en.mode, { selector: 'summary' }));
  fireEvent.click(screen.getByRole('checkbox', { name: MRA_DISTAL.en.mode }));
  expect(screen.getByText(MRA_DISTAL.en.loading)).toBeTruthy();
  expect(screen.getByTestId('simulation-vessels')).toBeTruthy();
  await act(async () => resolve(source));
  expect(screen.getByTestId('source-vessels')).toBeTruthy();
  expect(screen.queryByTestId('simulation-vessels')).toBeNull();
  expect(screen.queryByTestId('flow')).toBeNull(); expect(screen.queryByTestId('clots')).toBeNull();
  expect(screen.getByTestId('embolus')).toBeTruthy();
  expect(screen.getByTestId('keyboard').getAttribute('data-vessels')).toBe('false');
  expect(screen.getByText(MRA_DISTAL.en.badge)).toBeTruthy();
  expect({ occlusions: useApp.getState().occlusions, variants: useApp.getState().variants, map: useApp.getState().map }).toEqual(before);
  fireEvent.click(screen.getByRole('checkbox', { name: MRA_DISTAL.en.mode }));
  expect(screen.getByTestId('simulation-vessels')).toBeTruthy();
  expect(screen.getByTestId('keyboard').getAttribute('data-vessels')).toBe('true');
});
it('keeps the model display after a load failure and allows retry', async () => {
  mocks.load.mockRejectedValueOnce(new Error('offline')).mockResolvedValueOnce(source);
  render(<Scene3D sim={sim} />);
  fireEvent.click(screen.getByText(MRA_DISTAL.en.mode, { selector: 'summary' }));
  fireEvent.click(screen.getByRole('checkbox', { name: MRA_DISTAL.en.mode }));
  await waitFor(() => expect(screen.getByRole('alert').textContent).toBe(MRA_DISTAL.en.error));
  expect(screen.getByTestId('simulation-vessels')).toBeTruthy();
  fireEvent.click(screen.getByRole('button', { name: MRA_DISTAL.en.retry }));
  await waitFor(() => expect(screen.getByTestId('source-vessels')).toBeTruthy());
  expect(mocks.load).toHaveBeenCalledTimes(2);
});
it('excludes hidden or fully clipped source families and clears their focus', async () => {
  mocks.load.mockResolvedValue(source);
  render(<Scene3D sim={sim} />);
  fireEvent.click(screen.getByText(MRA_DISTAL.en.mode, { selector: 'summary' }));
  fireEvent.click(screen.getByRole('checkbox', { name: MRA_DISTAL.en.mode }));
  await waitFor(() => expect(screen.getByTestId('source-vessels')).toBeTruthy());
  act(() => screen.getByRole('button', { name: MRA_DISTAL.en.leftMCA }).focus());
  expect(screen.getByTestId('focus').getAttribute('data-position')).not.toBe('');
  fireEvent.keyDown(screen.getByRole('button', { name: MRA_DISTAL.en.leftMCA }), { key: 'Enter' });
  expect(screen.getByTestId('focus').getAttribute('data-position')).not.toBe('');
  expect(screen.getByRole('button', { name: MRA_DISTAL.en.leftMCA }).getAttribute('aria-pressed')).toBe('true');
  act(() => useApp.setState({ hemis: { l: false, r: true } }));
  expect(screen.queryByRole('button', { name: MRA_DISTAL.en.leftMCA })).toBeNull();
  expect(screen.getByTestId('focus').getAttribute('data-position')).toBe('');
  act(() => useApp.setState({ clip: { axis: 'x', pos: -100 } }));
  expect(screen.queryByRole('button', { name: MRA_DISTAL.en.rightMCA })).toBeNull();
});
